### ISSUE TITLE
Two typos in the "about"  page

### ISSUE THREAD

**Issue by vcvpaiva** [Carnap/Carnap#1]
1. "stipulate" is mispelled in "Carnap is a free and open-source Haskell framework for creating and exploring formal languages, logics, and semantics. It lets you quickly and straightforwardly define languages, construct logics for those languages, and stipluate their semantics."

2. Montague has a typo in "This is a proofbox with a Kalish and Montegue System for Propositional Logic. "

**Comment by gleachkr** [comment]
Thanks @vcvpaiva! Much appreciated.
