### ISSUE TITLE
Use onbeforeunload on problem set pages

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#10]
If you leave or reload a page with assigned problems, all solutions not yet submitted get lost. Would be good to add a popup using onbeforeunload to warn the user before that happens.

**Comment by gleachkr** [comment]
I've implemented this, along with a related CSS change that causes submission buttons to "stay pressed" upon successful submission. I'll do a few more checks and deploy tomorrow.

It'd be good to round this out with another change that, upon page load, decorates the submission buttons for already-submitted problems. I'll look into the feasibility of doing that.

**Comment by rzach** [comment]
This is done, right? I'll make a new issue for making the visual feedback that an exercise is already submitted persistent.

**Comment by rzach** [comment]
See issue #78 for the persistent submitted feedback issue

**Comment by rzach** [comment]
So I used a problem set page (as shared/ not assignments/) and lost 30 minutes of work in a Zoom session because I hit Ctrl-R by accident.  The `onbeforeunload` trap seems to be smart enough to not trigger when you didn't actually enter anything on the page. Maybe it should be on every page, not just assigned problem pages? (if not, maybe @dsanson can make a JS script available we can include in any page we want to make sure this doesn't happen.)

**Comment by dsanson** [comment]
It seems to me like Carnap should, by default and without any extra hacks, save work-in-progress locally, within the user's browser. And it should do this for all pages, not just assigned pages. I think the right way to do this is to use the web storage API. (When I get breathing room, I'm happy to look in to how to do this. But right now, breathing room is short.) <https://www.w3schools.com/html/html5_webstorage.asp>

**Comment by gleachkr** [comment]
In the short term, I think beforeunload on documents shouldn't be hard. I'll reopen and do that.
