### ISSUE TITLE
Minor bug in export grades feature

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#100]
If I click on "export grades", it starts calculating the grades, and shows me the progress. If I then start scrolling through students, while it is still calculating, it starts trying to calculate the scores for visible students. But that process seems to interfere with the original calculation: it stops calculating scores for non-visible students, so never completes.

**Comment by gleachkr** [comment]
Thanks! I found the issue. The "update" method of each row in the table ovewrites itself when called, in orrder to avoid unneeded updates.

But it was formerly overwriting itself with a "do nothing" function, when it actualy needs an "immediately indicate readiness" function to keep the export grades from locking up. I'll try to commit and deploy soon.
