### ISSUE TITLE
formatting for long multiple choice answers

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#102]
Long multiple choice questions overflow their box. See, for example, 1.9 and 1.10 in this document:

https://carnap.io/shared/dsanson@gmail.com/Arguments%20and%20Validity.md

![Screen Shot 2020-04-28 at 10 24 40 AM](https://user-images.githubusercontent.com/14331/80505835-7c9d1800-893a-11ea-95ff-4e8185467153.png)

**Comment by gleachkr** [comment]
Should now be fixed.
