### ISSUE TITLE
formatting for translation exercises

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#103]
Translation exercises often spill over the text above them. (This can be solved manually by adding a hard line break.) See, for example, exercise 2.1 on this page:

https://carnap.io/shared/dsanson@gmail.com/Chapter%202%20Review

![Screen Shot 2020-04-28 at 12 42 26 PM](https://user-images.githubusercontent.com/14331/80519766-1b7f3f80-894e-11ea-9b84-cb8b8968ca88.png)

**Comment by gleachkr** [comment]
It looks like this mainly happens following a pandoc "verbatim" pipe block, is that right? have you seen it in other places?

**Comment by dsanson** [comment]
Ah, good. That's probably right, as I have the habit of putting abbreviation schemes in verbatim blocks.
