### ISSUE TITLE
Document and automate build process

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#104]
- [ ] document the basic build process using stack, for those who can figure out how to install GHCJS.
- [ ] document the build process using the Carnap-Builder container.
- [ ] automate the steps in the process that can be automated.

For now, details can be found here:

https://groups.google.com/d/topic/carnap-users/bAQOlV4rhY0

**Comment by lf-** [comment]
Can you please repost the information from that link here? It's not publicly accessible.

**Comment by gleachkr** [comment]
Shall we close this?

**Comment by dsanson** [comment]
Yes!
