### ISSUE TITLE
Ability to reopen timed exams, grant extensions

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#107]
Sometimes, a student gets very close to the right answer, and I want to offer feedback (issue #101), and ask them to "fix" the problem. And sometimes, a student is so far away from the correct answer (e.g., submits an empty response to a qualitative question), that I want to just reset the problem and let them try again.

So, feature request:

-   an option, when grading problems, to manually "reopen" an individual problem.

I am not sure how this should interact with due dates: probably a sane default that extends the due date for that student, with configurable options.

**Comment by gleachkr** [comment]
This does seem like it would be useful. I think it'd be straightforward to allow an instructor to provide students with an opportunity for a do-over, by just deleting their incorrect submission.

The mechanics of giving due-date extensions for individual students is trickier. One approach that might work (since it seems like this would mostly be intended for exam environments, in which you want to allow for incorrect submissions) would be to use do-overs in combination with the new exam timers. You could give students another try at a timed exam by deleting the token that indicates their original access time. Do you think that'd work for this kind of use-case?

**Comment by dsanson** [comment]
The only thing I worry about with the implementation of just deleting the submission is how that might interact with the option to provide feedback on the submission. I was imagining that the feedback probably gets linked to the submission in the database.

I haven't explored the exam timers, but resetting the original access time seems like it might be a good solution in some cases but not others. FWIW, I'm not sure whether or not I plan, going forward, to giving timed exams. This term I've been using "quizzes" (using exam mode), and I effectively waived due dates, by setting them all to be "due" on the last day of the term. In that context, resetting due dates was not an issue, but the opportunity to provide feedback and allow resubmission was. In the Fall, I suspect I will do something similar: quite likely, untimed quizzes with tightened up due dates.

**Comment by gleachkr** [comment]
Thinking about this more, in connection with #101: 

I'm wondering if the best way to outsource a fair amount of complexity, and keep the server as simple as possible, would be to try to create a good workflow for emailing students with comments on their work, using mailto links.

That'd let the "delete problem for resubmission" approach work cleanly, and would probably prevent some mantainence overhead down the road. It'd also have some advantages, in that students could follow up with questions, and you could include attachments, links, images and so on in your comments.

What do you think? Any downsides I'm missing?

**Comment by gleachkr** [comment]
About due-date extensions, I think the way to go is probably to create a new kind of instructor-issued token (with an expiration time) that allows access to the assignment after the due-date.

**Comment by dsanson** [comment]
Outsourcing the complexity using mailto links might be a good idea. I have some anecdotal evidence that students are more likely to respond to emailed comments than to comments that they access through some web portal.

**Comment by gleachkr** [comment]
I've now added the ability to delete submitted problems (in the review area). Still need:

- [ ] Deletion of timed-test-tokens
- [x] Access tokens for extensions to due-dates

**Comment by rzach** [comment]
If I delete a submitted problem, does the student get to do it again? (I'm about to assign my first timed problem and expect I'll have to give students another try for various reasons eg internet breaks etc.)

**Comment by gleachkr** [comment]
They can redo deleted problems, but not after the timer is up. That would
require deleting the access token to "restart the clock". Sorry, will get
going on that ASAP.

**Comment by rzach** [comment]
No pressure I'll figure it out. Worst case I can make another problem set for them.
