### ISSUE TITLE
Equivalence calculus

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#109]
One of the things I have my students do is to transform a formula into normal form using "chains of equivalences" -- rewrite subformulas successively according to equivalences like commutativity, associativity, distributivity, etc.
I imagine that it wouldn't be too hard to implement this in terms of formulating and checking rules. But it would require a different setup: instead of premise and desired conclusion, we just provide the starting sentence and some info on what we want the ending sentence to be -- in CNF, DNF, perhaps minimal in some way.
Would it be hard to do this?

**Comment by JakeEhrlich** [comment]
I would guess that as one off instances for specific logics and normal forms like classical propositional logic and CNF/DNF this isn't too hard.

I did however figure out how to make it hard in case Graham didn't have enough work. I think all of these normal forms arise from a set of rewrite rules. A more general feature might be to setup rewrite rules where the left side of the rewrite rules is unified with target sentence and if it matches its replaced with the left hand side but with the substitution applied. You can also check that the free variables on the right hand side of the rewrite are a subset of the ones on the left to ensure the rewrite rule doesn't introduce improper variables. The rewrite rule can be applied as if by [rewrite in plated](http://hackage.haskell.org/package/lens-4.19.2/docs/Control-Lens-Plated.html#g:2) (or perhaps even directly by that if it works out). For student's sake showing the steps might be a good idea if the goal is to explain normal forms by rewrite rules.

This could be as a general mechanism that each logic can employ or perhaps as a general mechanism like the ability to define your own inference rules. (That's of course even harder still mind you)

**Comment by gleachkr** [comment]
Hey Jake! What you're describing might actually be pretty close to how we [prenex-ify](https://github.com/gleachkr/Carnap/blob/81a60f86951fa034a37bb1eeca661a2d7023a0b2/Carnap/src/Carnap/Languages/PureFirstOrder/Util.hs#L58) formulas for equivalence checks in translations (right down to the use of plated!) except that that process use prisms rather than unification to get a bunch of language-agnostic rewrite rules.

Using unification to specify the rewrites is probably better, though, since then as you say, it'd be possible to specify rewrite rules at run-time by basically parsing the scheme that we're unifying with on the LHS, and the scheme that we're applying the substitution to on the right. That'd be super slick actually.

As a first step towards what Richard is thinking of, I wonder if we could bascially factor his request into two features:

- [x] A setting for the proof-checker, alongside "playground" and "proofcheck" in which the conclusion of the proof only needs to pass some test. The test could be any one of those allowed for translations, as long as it makes sense for the language of the proof.

- [x] A new "hilbert" proof format, analogous to fitch/montague/lemon, in which the proof is just a series of unindented lines, and there's no notion of subproof. Probably you'd want two flavors, one where you cite prior lines, and one where you're assumed to be depending on the immediately preceding line.

I think if you put those two together, and had a proof system in which the only rules were equivalence-preserving, you'd be able to do chain-of-equivalence exercises. I can also imagine uses for the two features independently...

**Comment by rzach** [comment]
I noticed that the original forall x system SL+ has all the rules I need except associativity and distributivity. With the first setting you mentioned, I'd be happy. (They'll just have to always put the preceding line number in and I'll tell them not to use subproofs.)

**Comment by rzach** [comment]
I don't know how much time it would take to implement the second thing only (an `Equiv` proof system where you apply an equivalence transformation to the preceding line).  I can totally live without it but I am coming up to the time where I'm covering it (in 2 weeks).  If I had that my students could check their work before submitting a screenshot.

Like I said, totally can live without it.  Just thought I'd check.

**Comment by gleachkr** [comment]
Thanks for the heads up. I'll bump it up in the queue!

**Comment by rzach** [comment]
I think it would be nice to have in addition to the rules in forallx SLPlus:

- distributivity
- associativity
- negated conditional ~(A->B) = (A /\ ~B)
- idempotence A /\ A = A, A \/ A = A
- absorption A /\ (A \/ B) = A, A \/ (A /\ B) = A

**Comment by gleachkr** [comment]
Any notational preference for these rules?

**Comment by rzach** [comment]
How about:

DeM for DeMorgan
Dist for distributivity
Assoc for associativity
Comm for commutativity
Id for idempotence
Abs for absorption
Cond for equivalences involving conditionals (A->B) = (~A \\/ B); ~(A -> B) = (A /\ ~B)
Bicond for (A <-> B) = (A -> B) /\ (B -> A)

If it's not hard to do can you allow Dist and Abs work with implicit commutativity ie
A /\ (B \\/ A) = A but also A /\ (A \\/ B) = A and (A \\/ B) /\ A = A and (B \\/ A) = A
A /\ (B \\/ C) = (A /\ B) \\/ (A /\ C) and also (B \\/ C) /\ A = (B /\ A) \\/ (C /\ A)

The ZachTFL (pre 2019) parser that doesn't implicitly do Associativity should probably be used, otherwise it gets confusing -- unless DeM and Dist can be made to work with more than two conjuncts/disjuncts.  I'm guessing that's hard.

I would ask for a system that maybe can also deal with quantifiers (ie QN rules for replacing ~Ax with Ex~ and ~Ex with Ax~). However the 2019 FOL parser has implicit associativity and the pre-2019 parser has the old syntax (Fa instead of F(a)) so that would requiring adding a parser that uses the 2019+ syntax but also disallows associativity.

Those last two things are not important for now, but if they can be done, I can file an issue for them for later. If not, no problem.

**Comment by gleachkr** [comment]
Sure thing. Implicit commutativity is now incorporated. A first-order version with QN would be pretty easy, I'll try that next.
Is `ZachPropEQ` an OK name for the system?

**Comment by rzach** [comment]
Yeah that's great, wonderful.

If it's not too much to ask can I also have rules `Simp` to simplify things?
```
P /\ (Q \/~Q) = P
P \/ (Q \/ ~Q) = (Q \/ ~Q)

P \/ (Q /\ ~Q) = P
P /\ (Q /\ ~Q) = (Q /\ ~Q)

P /\ (Q /\ ~Q) = (Q /\ ~Q)
P \/ (Q \/ ~Q) = (Q \/ ~Q)
```

**Comment by gleachkr** [comment]
OK, ready for testing! Invoke with

    ```{.ProofChecker .ZachPropEq}
    1.1 P:|-:~~(P\/P)
    ```

The justification for a premise is `Pr`. Each non-`Pr` line automatically depends on the preceding line (so no line number citations are necessary). I added implict commutativity to the `Simp` rule. This ends up giving the rule 32 variants, which didn't cause any trouble in testing on my end, but could conceivably cause it to be a little slow.

**Comment by rzach** [comment]
Amazing. Seems to work fine, even as a .Playground. Of course, I couldn't test all of the combinations, but I have an army of students standing by ;)
Can we have Carnap (also) accept "PR" as a premise as well (since students are used to that), perhaps even make the rule names case-insensitive if that's easy to do?
Is the proofcheck-but-only-test-last-line thing easy?

**Comment by gleachkr** [comment]
Sure, making the rule names case insensitive shouldn't be hard. I'll update the parser tomorrow.

Not totally sure how hard to proofcheck-but-only-test-last-line thing will be, but probably not too bad. Might still take a day or two. Should I prioritize that, or `ZachFOLEQ`?

**Comment by rzach** [comment]
The proofcheck-test thing, please & thank you.

**Comment by gleachkr** [comment]
OK, should be ready for testing. The new attribute for tests is `tests`, and you can write `tests=...` for any set of tests that work with translations. I've changed `Pr` to `PR`, but I haven't done the case insensitivity yet. So, remaining is, I think

- [ ] `ZachFOLEQ`
- [x] case insensitivity.
- [x] feedback for students about which test is failing.
- [ ] maybe a better way of displaying the problem visually than just showing the sequent.

**Comment by rzach** [comment]
How do I enter the problem? Like, what goes on the right of the turnstile?
```
~~~{.ProofChecker .ZachPropEq options="resize render fonts" tests="CNF" points="1"}
PS12.7 ~((A <-> B) -> (B \/ ~ C)) :|-:
~~~
```

**Comment by gleachkr** [comment]
Anything should be fine, or you can leave it blank.

**Comment by rzach** [comment]
Ah ok! But you need the turnstile right? 
If you have `tests` it'll accept it once a line meets the test, and if you don't have `tests` it will accept it once you reach the sentence on the right of the turnstile?

**Comment by gleachkr** [comment]
Correct! I'm not sure what to do visually about the turnstile - it's a little confusing in the test-only setting.

**Comment by rzach** [comment]
Works like a charm! Thank you so much.

**Comment by rzach** [comment]
I'll get started on documenting it. (I think I gave you two of the simplification rules twice, not sure if you caught that.)

**Comment by gleachkr** [comment]
Feedback about which test is failing should now appear on a mouse-hover over the ⚠ sign.

**Comment by gleachkr** [comment]
For the FOL equivalence calculus, maybe also the "rules of passage", like ∀x(φ∧ψ(x)) ⊣⊢ φ∧∀xψ(x)?

**Comment by rzach** [comment]
Oh yes that'd be cool. This is the list of equivalences I hand out. Am I missing anything?  Not sure how hard testing variable renaming is (re not renaming into a variable which already is bound in the place where you're renaming)
[279-equivalences.pdf](https://github.com/Carnap/Carnap/files/5613546/279-equivalences.pdf)

**Comment by gleachkr** [comment]
Looks good! All pretty straightforward. Variable renaming is no problem, but there's one thing that might be a little surprising to students. Carnap actually only looks at quantified formulas up to α-equivalence, so every inference technically allows for implicit variable renaming. I've included `VR` as the repetition rule, though, so deductions for the system you've got will still all be correct. I also added implicit commutativity to the `QSA`/`QSE` rules. I'll try to deploy tonight or tomorrow morning.

**Comment by gleachkr** [comment]
OK, should be good to go under `.ZachFOLEq`.

**Comment by rzach** [comment]
It's taking very long to check. https://carnap.io/shared/rzach@ucalgary.ca/equivalences.md

**Comment by gleachkr** [comment]
Specifically with the proof in Ex2?

**Comment by rzach** [comment]
Yes, I think it's been spinning for 20 minutes. Also, is the PNF test implemented?

(The FOL stuff is not urgent at all for me so if you want to save this for later it's ok with me.)

**Comment by rzach** [comment]
I think what's blocking is the VR check.

**Comment by gleachkr** [comment]
Ok, thanks. I'll check it out soon.

**Comment by gleachkr** [comment]
> I think what's blocking is the VR check.

Yep, I think this is right. It still won't be super fast, but this part is where it's hanging, I think.

**Comment by rzach** [comment]
I also tried this:
```
~(Ax P(x) <-> Ey Q(y)) :PR
~((Ax P(x) -> Ey Q(y)) /\ (Ey Q(y) -> Ax P(x))) :Bicond
~(Ax P(x) -> Ey Q(y)) \/ ~(Ey Q(y) -> Ax P(x)) :DeM
~(Ax P(x) -> Ey Q(y)) \/ (Ey Q(y) /\ ~Ax P(x)) :Cond
~(Ax P(x) -> Ey Q(y)) \/ (Ey Q(y) /\ Ex~ P(x)) :QN
~Ey(Ax P(x) -> Q(y)) \/ (Ey Q(y) /\ Ex~ P(x)) :QSE
```
The propositional lines took about 10 sec, the QN about 20, the QSE line has been going for several minutes.

**Comment by gleachkr** [comment]
One simple way to improve these would be to eliminate all the implicit commutativity, to cut down on the number of cases.

**Comment by rzach** [comment]
The commutativity of the quantifier + /\ and \/ shifts is probably needed. But what we could do is to split them by quantifier/connective pair and give them different names. Then QSA(ll)O(r) (say) would only have to check 4 equivalences rather 50 or whatever.

**Comment by rzach** [comment]
(Assuming you mean that the checker doesn't care if the quantifier is in the left or right disjunct.  If it's actually implicit commutativity, e.g., it accepts Ax P(x) \/ Q = Ax(Q \/ P(x)), then yeah we don't need that commutativity.

**Comment by rzach** [comment]
Also the FOL2019 parser has implicit associativity -- that doesn't make a difference though does it?

**Comment by gleachkr** [comment]
> Also the FOL2019 parser has implicit associativity -- that doesn't make a difference though does it?

Nope, it shouldn't. I think the equvalence system should also be using a parser that doesn't assume associativity.

**Comment by gleachkr** [comment]
> the QSE line has been going for several minutes.

This one looks like another bug.

**Comment by gleachkr** [comment]
Fixes for the VR and QSE bugs are now deployed.

**Comment by gleachkr** [comment]
Just a small update. I played around a little and wasn't happy with where this ended up even after breaking up the rules. So I've dug into Carnap's implementation of Huet's algorithm, and found a couple of opitimizations.

The optimized Huet now handles Ex2 in about 4 seconds on my computer, down from about 80 seconds, while keeping all the cases of the various rules. I'd like to keep testing it a bit, since I don't want to break the proof checker in the middle of anyone's final exam, but if I can't find any issues I'll try to roll it in a few weeks.

**Comment by rzach** [comment]
Just pinging this since I don't think it's deployed and we have a limited window now before the term starts up again. I've put the file (perhaps prematurely) into the documentation: https://carnap.io/srv/doc/equivalences.md

**Comment by gleachkr** [comment]
Yep, I noticed. I've been testing, and haven't seen any problems. OK if I do one more pass, and deploy tomorrow?

**Comment by rzach** [comment]
Sure, I don't actually need the PNF stuff (yet) but someone might want to use it.

**Comment by gleachkr** [comment]
OK, deployed!

**Comment by rzach** [comment]
Nice and fast!

I think the only thing that's maybe still a bit confusing/ugly is that it has a \bot on the right if there is no target formula.

**Comment by rzach** [comment]
I think this can be closed, unless you want to keep it open for the \bot on the right of the turnstyle? (Maybe it can be displayed as a ? for this system?)

**Comment by gleachkr** [comment]
Implemented that suggestion for handling ⊥! So I think this is done. :tada:
