### ISSUE TITLE
Render proof when loading

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#11]
When Carnap first displays a proof edit box, and `options="render"` is given, it should also render the content of the box (which may be nonempty if hints are given).

**Comment by gleachkr** [comment]
I suspect part of doing this right involves addressing #12, but I wonder if using `init="now"` helps with this?

**Comment by rzach** [comment]
Ah, yes, it does. My bad, I checked only the options section of the documentation and didn't see the `init` stuff later on.
