### ISSUE TITLE
Make ZachFOL2019 systems more liberal

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#111]
After making students do two semesters of quite involved symbolizations where they had to put in all parentheses I'm tending toward going a bit easier on them and allowing conjunctions and disjunctions of more than 2 formulas. Can that be done for translation exercises only or would it have to cover both translation and proofs?

**Comment by gleachkr** [comment]
For the translations: would it work to add some understood associativity to those operations, so that a string like "P∧Q∧R" parses as (P∧Q)∧R?

It'd be easy to have two variants of the formal system, one with a relaxed parser and one with a strict parser, if you prefer the strict parser for proofs. They would need to have different names, but you could just use a suffix, like `ZachFOL-Lax-2019` maybe. 

Would something like that help?

**Comment by rzach** [comment]
I think if I tell students that (A /\ B /\ C) is short for ((A /\ B) /\ C) but that they should try to put in all parens explicitly nothing bad will happen. (My decision to not allow this at all was because I was worried that I'd have to liberalize the inference rules, too, e.g., allow A, B, C |- A /\ B /\ C.)
What will Carnap do with formulas that have the parentheses given explicitly? Eg if I ask students to do a proof of `:|-: (~A \/ B) \/ A` will that display as ~A ∨B ∨ A?

**Comment by gleachkr** [comment]
If the parser has some associativity, then Carnap will treat "A/\B/\C" and "(A/\B)/\C" the same--it'll quite happily accept either.

Without any other changes, those will both render (when displaying a proof, for example) as "(A∧B)∧C". You could change the formula renderer to take associativity into account, but this would be a different set of tweaks from adjusting the parser.

**Comment by rzach** [comment]
Ah good. I just want students to be able to enter things without all the parentheses, but would like to always display all the parentheses in formulas given, so this works out perfectly. I think I doesn't hurt to implement it on the ZachFOL2019 parser, no need for a new one.

**Comment by gleachkr** [comment]
Great! Will do.

**Comment by gleachkr** [comment]
Should be closed by 24ad9836c646c9092be529f39081161abf277e17

**Comment by rzach** [comment]
Is it deployed?

**Comment by gleachkr** [comment]
Yep, as of a moment or two ago.
