### ISSUE TITLE
Custom CSS in documents

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap#112]
Pandoc documents should allow users to specify a custom css file, in order to make it possible to carefully style user-developed books.

- [x] Custom CSS in document view
- [x] Custom CSS in assignment view
- [x] allow user to post css files as shared documents
- [x] documentation

**Comment by orbit-stabilizer** [comment]
We're looking to create our custom stylesheet - should I be looking at following commit: e66feb230bec73c9f21402b6df9a6c9553c2e13d, to understand how to add the css file?

**Comment by gleachkr** [comment]
Probably shouldn't be necessary to dig through the code. I'll go ahead and
finish the documentation for that today and post a link here.

**Comment by gleachkr** [comment]
OK, here's the link!

https://carnap.io/shared/gleachkr@gmail.com/carnap-pandoc.pandoc

the documentation is at the bottom, under "other features".
