### ISSUE TITLE
Support the U. Pittsburg Forall x

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap#114]
- [x] Propositional Core
- [x] Propositional Derived
- [x] First Order Core
- [x] First Order Derived
- [ ] Documentation

**Comment by rzach** [comment]
I have heard that Pitt has adapted forall x:YYC but haven't seen it. Are they using different rules/rule names/etc? (At some point the forallx dialects might get too unwieldy to keep track of, so maybe we can standardize?)

**Comment by gleachkr** [comment]
The rule names are shuffled around a bit. In the propositional system, I think IP (from forall x:YCC) has become ¬E, ¬E has become ⊥I, X has become ⊥E, and it's otherwise the same. In the FOL system, the identity rules are eliminated, but otherwise the same.

**Comment by rzach** [comment]
That is just wrong ;)

**Comment by gleachkr** [comment]
Closing in favor of https://github.com/Carnap/Carnap-Documentation/issues/5
