### ISSUE TITLE
Authentication improvements

### ISSUE THREAD

**Issue by lf-** [Carnap/Carnap#116]
Hi!

I have been poking through authentication details for Carnap to try to figure out if we can use it for homework in the quite-distant future (the immediate goal is getting an online textbook working without doing evaluation/homework yet). I am assuming that for FIPPA compliance reasons our implementation cannot use Google as an authentication platform. My university offers SAML2 based authentication via Shibboleth/IdP v3, which is probably what would need to be used in such an implementation (self hosted) but I will get to that when I get deeper into this.

This is a roadmap for what I think I need to do for this (not an expert in this codebase by any means!):

- [x] Google authentication can be disabled, turning off the login page and authenticated functionality if no auth is configured (this is just to avoid confusing users)
    - initial baby step in this is #117 which removes the requirement for building for production of setting Google tokens (trying to login will 400 if none are configured)
    - We still need some auth provider for admin login, which I am not comfortable using LTI for. Google is good enough for this purpose for now, at least on my side. Email+Password auth wouldn't resolve students accidentally making extra accounts when the installation is LTI-only [as is likely going to be the case with the UBC deployment eventually]. Maybe support disabling google login for non super admins or instructors in the config file?
- [x] Change the identifier used for authentication to a stable non-email ID of some sort — This is effectively the case with yesod-auth already as long as our `ident`s don't overlap, which they cannot in my LTI implementation using `id@@issuer`
    - [x] Remove the [hardcoded checks against Graham's email](https://github.com/gleachkr/Carnap/blob/a20539ddfd4e61fec89fb5040650d25f228b9efd/Carnap-Server/Foundation.hs#L114) — Done in #166 😅
- [x] Add support for multiple authentication providers — ±Done in #157 by adding LTI
- [x] Add support for SAML2 or LTI (unsure as to if this is good for auth, need to further investigate) or other methods of auth — LTI implemented, it's very easy to use and allows for lots of future possibilities :)

**Comment by gleachkr** [comment]
All this sounds great. For LTI: it might be worth exploring OAuth2. This [appears to be suppported by Canvas](https://canvas.instructure.com/doc/api/file.oauth.html), and to be part of some of the LTI standards, so it's likely supported by other LTI platforms.

There's pretty good [Yesod support](https://hackage.haskell.org/package/yesod-auth-oauth2) for oauth plugins. And I bet they'd accept PR for a Canvas or LTI (whatever turns out to be possible) plugin upstream.

**Comment by lf-** [comment]
Very good catch! Yes, it looks like our Canvas implementation does log people in through LTI and presumably OAuth which I bet is a lot easier to implement on our end vs SAML2.

**Comment by dsanson** [comment]
Is this something that you are actively working on, @lf-, or still something for the distant future? My haskell is weak indeed, but looking at yesod-auth-oauth2 makes it look not that complicated.

**Comment by lf-** [comment]
@dsanson funny you ask! I just got finished my other project and want to have a crack at this one next. We'll see where that takes us this week.

**Comment by lf-** [comment]
@dsanson see #157

As it turns out, it was not OAuth2, but a weird version of OpenID Connect.

**Comment by gleachkr** [comment]
About the remaining unchecked item: what are the concerns with using LTI for admin login?

**Comment by lf-** [comment]
Primarily the accounts not necessarily staying around and their inconvenient association of LTI accounts with a single course, which is not good for administrators and instructors who are involved in multiple courses. It's possible to do, even simple, but I think the footguns are too big.

There's also the chicken and egg problem where you can't create the initial admin account via LTI because you need an admin account to configure LTI, which was the initial reason I chose not to support it.

**Comment by lf-** [comment]
My current view on it is I want to disable creation of new accounts via Google, with a runtime config setting on the admin page, and maybe add a box to the admin page to create User records by email so you can invite one Google user at a time for instructor purposes. If someone tries to make a new Google account we can show a message saying "this Carnap instance uses LTI for login, please log in using your learning management system". 

I'm not a fan of config file settings for stuff that can change often because they require logging into the server which is inconvenient for my setup, as effectively all the sources of config data are immutable and require a new deploy (as they don't need to be mutable).

**Comment by gleachkr** [comment]
Hey, does the new runtime settings complete this one?

**Comment by lf-** [comment]
> Hey, does the new runtime settings complete this one?

Effectively, yes!
