### ISSUE TITLE
Render more of a proof

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#12]
Carnap will render a proof line only if both a sentence that parses correctly and a valid rule are given. When constructing proofs strategically (from the bottom up), you often write down goals but don't have the justifications for them. You may write a `?` to indicate a missing line (which won't parse as a sentence).  Instructors may also provide partial derivations where either the sentence or the justification is missing. 

In such cases it might be good if Carnap also rendered the incomplete lines. Otherwise the rendered proof looks nothing like the partial proof in the editor, and so it's hard to see what you're doing or are supposed to (still) do.

**Comment by rzach** [comment]
Can Carnap try to render anything that parses as a correct formula nicely (and without quotation marks)?

**Comment by gleachkr** [comment]
Yes, that would be better. I've put something together. I'll test it a little more, and try to deploy ~tomorrow~ ASAP (today turned out to be pretty busy).

**Comment by gleachkr** [comment]
OK. Adjusted with b5f0182. If what's on the line parses as a formula, Carnap now provides the formula to the proof renderer, but generates a parsing warning (in the feedback column, with or without proof renderer) that a rule citation is expected. This applies only to Hardegree, Fitch, and Montegue systems; the individual lines in Lemmon systems are a little more complicated, so I'll leave them unparsed when partial for now.

**Comment by gleachkr** [comment]
I think this can now be closed. Feel free to reopen if not.
