### ISSUE TITLE
Unify (& make printable) success feedback

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#127]
Translation exercises (as per #19) show a checkmark next to the solution as well as turning the background green when the solution has been checked and is correct. Add the checkmark feedback to all other exercise types, that is: add the `success` class to whatever `div` contains the output as well as `::after`.

This will make printouts contain the information which problems have been completed, and will also help students who might not be able to see green or contrast well. Since it's done with CSS, users can change what happens. (Perhaps the class `success` should be set on the entire `exercise` div?)

**Comment by gleachkr** [comment]
This is now updated for all the exercises that had success feedback. The sequent calculus exercises still need success feedback, so I'll open a separate issue for that, to pair with your issue about the syntax checker.
