### ISSUE TITLE
Make it harder to accidentally replace shared files

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#13]
Something that now has happened to me multiple times: I work on a problem set, click the "edit this document" cog icon, upload the file to overwrite the old version on the server, discover that I've accidentally replaced a different, live problem set.

I also noticed that (in Firefox) the file name of the "Browse" button in the "Replacement file" dialog is prepopulated with the name of the file last uploaded, not the name of the file you're replacing. Also, the "Update Shared Document" dialog doesn't tell you which file you're updating. So if you've just uploaded Assignment2.md and then update Assignment1.md the dialog will say "Browse: Assignment2.md" and not complain if you're overwriting Assignment 1 with Assignment 2.

Proposed solution to make this harder to do: 
- Display name of file to be replaced in "Update Shared Document" popup
- When replacing a file, check if the file name of the original and replacement are different and display a warning (say, in red, below the browse button) if they are.

**Comment by gleachkr** [comment]
This should now be fixed by 40faad2591bd6e5a993a26602c510066112cf0ae.
