### ISSUE TITLE
Checklists

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#131]
Our online teaching people say that our students really like the "checklist" feature in Sakai's "lessons" module. Seems like it would be easy to implement in Carnap. The idea is that the student gets a "todo" list at the top of the page, e.g.,

-    Watch video
-    Read chapter 1
-    Post two questions to the forum
-    Complete problem set 1

But it is formatted as a checklist, not just a bulleted list, and they can check off each task as they complete it, so they can keep track of what they have done and what they still need to do.

So, for Carnap, this would be a new exercise type, with a few unique features:

-    "answers" would be automatically and immediately submitted (checking the box suffices, you don't also need to click a submit button)
-    "answers" can always be changed (the student can "uncheck" a checked box)
-    the current "answer" would always be displayed to the student, in the form of the box showing up as checked or unchecked.
-    by default, these "exercises" are not worth any points

**Comment by gleachkr** [comment]
I wonder, how much of this would be covered by adding task_lists as a pandoc extension?

https://pandoc.org/MANUAL.html#ordered-lists

adding persistance  for all task_lists (so that the checked boxes persist no matter how the student is logs in) would be another step, but certainly doable. Would this cover it, you think, or are there additional advantages to implementing this as a type of exercise?

**Comment by gleachkr** [comment]
In the general spirit of making room for more instructor-provided javascript applications, I actually wonder about adding a general database entry for assignment state, where an assignment state would just be a JSON blob that could be updated and retrieved by client-side JS within the assignment. That could be used to store checklist state, problem submission state (as in #78), and I bet other things as well, in the future.

**Comment by dsanson** [comment]
I don't think pandoc's task_lists are actually interactive in any way? So adding pandoc's task_lists extension, plus some javascript to make them interactive, plus some javascript interaction with the database to make them persistent? Probably all or almost all doable client-side once you implement custom javascript.

**Comment by gleachkr** [comment]
Another use for assignment state: saving incomplete student work.

**Comment by gleachkr** [comment]
OK, I've enabled the task_lists extension.

**Comment by dsanson** [comment]
Oh, great! I've created a script for persistent checkboxes, and put it here:

https://github.com/dsanson/carnap-javascript

I should probably modify the script to put checkbox information into its own namespace inside AssignmentState, so it doesn't conflict with other possible uses of this feature.

One problem with using the task_lists extension is that pandoc doesn't provide any way to uniquely identify each checkbox. In the script, I use the value attribute of each checkbox, so the list needs to be raw html. I don't want to use the text content of each item, since that might get edited. But perhaps the best thing to do is to use pandoc's support for bracketed spans, so use a syntax along these lines:

```
-    [ ] Read the syllabus[]{data-value="syllabus"}
```
Is `bracketed_spans` enabled? No big deal if it is not, as I can always use raw spans:

```
-   [ ] Read the syllabus<span data-value="syllabus"></span>
```

**Comment by dsanson** [comment]
I've worked on the script a bit more, and I think it is now pretty solid. Here is a sample document that describes the features:

https://carnap.io/shared/dsanson@gmail.com/Checklist%20Example

I'm not sure what trade-offs there are in enabling more pandoc extensions, but it would be helpful to have `link_attributes` and `bracketed_spans` enabled, too.

**Comment by gleachkr** [comment]
No major downsides I can think of, and I bet they'll be useful with other JS extensions. I'll switch them on tomorrow.

**Comment by gleachkr** [comment]
OK, they should be live.

**Comment by gleachkr** [comment]
Is this one ready to close?
