### ISSUE TITLE
Option to use double turnstile in truthtables

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#140]
Some textbooks use the double turnstyle for semantic validity, and the single turnstyle for derivability. So it would be nice to have an option to use the double turnstyle with truthtables.

**Comment by gleachkr** [comment]
Should probably also be an option for the model checking exercise.

**Comment by dsanson** [comment]
Perhaps the default symbol used should depend on the system option, since each system tends to be tied to a primary textbook that uses that system?

**Comment by dsanson** [comment]
Closing this in light of 09c8b9f58941b35797c20fca00c72ae7c4cad54a.
