### ISSUE TITLE
Javascript Extension Documentation

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap#144]
It would be good to have a documentation file with links to some of the javascript extensions implemented by @dsanson.

**Comment by dsanson** [comment]
Might be premature. They are definitely not ready for prime-time yet. I never quite got the save-work script to work. And I need to rework the both the checklist and the save work scripts so they don't clobber each other when updating AssignmentState.

**Comment by gleachkr** [comment]
OK, good call. I'll close this, and maybe we can reopen later.
