### ISSUE TITLE
No feedback when citing a separator line

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#15]
Entering the line number of a subproof separator `--` should produce some kind of feedback. Right now it doesn't, there's not "attention" triangle or "incorrect" X next to such a line. See line 9 below:

![Screenshot from 2019-09-23 13-16-58](https://user-images.githubusercontent.com/3122348/65455471-8559c880-de04-11e9-803b-e9fc5a4d418c.png)

**Comment by gleachkr** [comment]
Ideas for feedback? It's nice that the column is uniformly plusses unless something is wrong, so maybe just a plus?

**Comment by rzach** [comment]
I meant that there is nothing next to lines 9-11 rather than warning triangles. Line 9 should say something akin to whatever happens when you cite the wrong number of lines. Eg "You are citing line 7, but that line does not have a sentence on it"?

**Comment by gleachkr** [comment]
Ah! OK, I see. Yes, that's right - will fix.

**Comment by gleachkr** [comment]
Should be fixed by aef32fb520fb9bda0abd961ec719342babe32712
