### ISSUE TITLE
Accept >I, >E, |I, |E for if, or rules

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#16]
Carnap allows entering \/ also as | and -> also as > and =>. But it doesn't accept |I, |E, =>I, =>E, >I, >E as rule names in the forall x: Calgary proof systems.

**Comment by gleachkr** [comment]
Right, makes sense. Those alternatives should now be accepted by the Calgary systems. Closed by d966292a8b33aac35c723722cd4b67b2df80d954.
