### ISSUE TITLE
Exporting grades requires scrolling through all students

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#161]
I'm not sure when this bug popped up, but it is similar to #100. In order to export student scores as a CSV, I need to slowly scroll through my list of students, so each student entry gets a chance to load.

**Comment by gleachkr** [comment]
I'm having a little trouble reproducing - it seems like pressing export grades starts the grade download, with the number of students loaded gradually ticking up (though you can speed things up a bit my scrolling through the students).

Is this what's happening for you? If not, any tips on reproducing this issue?

**Comment by dsanson** [comment]
Interesting. That is now what is happening. I *believe* it was stalling completely for me earlier. But it could just be that it was slow, and I didn't attend to the counter. I'll close this issue!
