### ISSUE TITLE
Sentence Letters: book vs. system

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#162]
I think I ran into this last Spring, but never thought to resolve it. I just looked at the documentation for the Carnap Book system, and see that it says that sentence letters are P...W instead of P...Z, while the Book itself says that the sentence letters are P...Z.

This isn't a big deal, but it is surprising! 

I created some translation problems that included Z in the scheme of abbreviation (P: I wear pants; Q: I attend class; Z: Class is on Zoom), but got a bunch of unexpected syntax errors.

**Comment by gleachkr** [comment]
Thanks! This is because X,Y,Z are reserved for the second order system. I'll go ahead and fix the book.
