### ISSUE TITLE
checksyntax seems to break exam mode

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#163]
Just posted an assignment with these settings:

````
```{.Translate .Prop points="10" options="exam checksyntax"}
T3.1 ~Q : It is not the case that it is hot.
```
````

I think this is suppose to allow incorrect submissions, as long as they are syntactically well-formed? But instead, it just doesn't accept incorrect submissions, as though it isn't in exam mode at all.

**Comment by gleachkr** [comment]
I just gave this a try, and wasn't able to exactly reproduce. But I did notice a UI issue that might explain this. `exam` doesn't actually prevent you from checking the correctness of your answer, even if it lets you submit an incorrect answer. So, `exam checksyntax` has the following effect (or should): you can check your answer with return, and submit incorrect work, but only incorrect work that's syntactically correct.

I think to disable the check entirely, the `nocheck` option is needed.

Does all that agree with what you're seeing?

**Comment by gleachkr** [comment]
OK to close this?
