### ISSUE TITLE
Enable pandoc_title_block and/or yaml_metadata_block

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#168]
It would be nice to let the browser know the page title. If `pandoc_title_block` or `yaml_metadata_block` were enabled, we could put the title author etc. in using metadata blocks in the markdown source as described at https://pandoc.org/MANUAL.html#metadata-blocks

**Comment by gleachkr** [comment]
We do have yaml metadata (added to support external css and js) so I think it's just a matter of scanning the block for the relevant fields and adding those to the produced html.

**Comment by dsanson** [comment]
See also #115.

**Comment by rzach** [comment]
Right this is a duplicate of #115 then sorry!
