### ISSUE TITLE
Parser treats whitespace inconsistently

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#17]
The parser does not accept a space after a negation, e.g., `~ P`. This seems unintuitive: it should ignore extra whitespace, the way it does around `&`, `Ax`, etc.

Incidentally, the parser seems to insist on a single space after `not`: so `not(P & Q)` and `not  P` (two spaces) are ungrammatical, but `not (P & Q)` parses ok.

**Comment by rzach** [comment]
Also noticed that thomasBolducAndZachFOL2019 doesn't like space between arguments. It should probably accept say `P(a, b)` as grammatical.

**Comment by rzach** [comment]
Also, space between quantifier and variable should maybe also always be allowed.

**Comment by gleachkr** [comment]
Should all be addressed by a988b8e360021ac9c30866ce85473ef29ee13e99. If there are any other whitespace issues that come up, feel free to reopen.
