### ISSUE TITLE
Make a .SequentPlayground

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#172]
As per discussion in issue #57 would be nice to also have a playground for sequent proofs.

**Comment by gleachkr** [comment]
I've implement initial support. Here's an example invocation, with a prepopulated proof.

    ```{.SequentPlayground .propLK init="now"}
    {"ident":11,"label":"P->Q,P:|-:Q","rule":"->L","forest":[{"ident":12,"label":"Q,P:|-:Q","rule":"Cut","forest":[{"ident":13,"label":"R,P,Q:|-:Q","rule":"XL","forest":[{"ident":58,"label":"Q,P,R:|-:Q","rule":"WL","forest":[{"ident":59,"label":"Q:|-:Q","rule":"Ax","forest":[{"ident":14,"label":"","rule":"","forest":[]}]}]}]},{"ident":14,"label":"Q,P:|-:Q,R","rule":"XR","forest":[{"ident":57,"label":"Q,P:|-:R,Q","rule":"WR","forest":[{"ident":10,"label":"Q,P:|-:Q","rule":"WL","forest":[{"ident":12,"label":"Q:|-:Q","rule":"Ax","forest":[{"ident":13,"label":"","rule":"","forest":[]}]}]}]}]}]},{"ident":15,"label":"P:|-:Q,P","rule":"WR","forest":[{"ident":16,"label":"P:|-:P","rule":"Ax","forest":[{"ident":11,"label":"","rule":"","forest":[]}]}]}]}
    ```

**Comment by rzach** [comment]
It's rendering the playground at the end of https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20LK.md but there doesn't seem to be anything to start from.  If it's not prepopulated it should probably be populated by an empty node or empty sequent.

**Comment by gleachkr** [comment]
There should be something there, but it looks like it's not handling the unprepopulated case well. The error in the playground might be affecting other exercises, so it might be a good idea to remove it for now. I'll try to fix this case.

**Comment by gleachkr** [comment]
Looks like an easy fix. I'll deploy something in a minute.

**Comment by gleachkr** [comment]
OK, deployed - your playground should now be working.

**Comment by rzach** [comment]
Looks like it's working!

**Comment by gleachkr** [comment]
closing in favor of #175
