### ISSUE TITLE
Sequent checker issues

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#175]
I'll add them here as I find them:

- [x] If the left side of the target sequent is empty, the automatically prepopulated sequent should have an empty left side. It now has a T in it.
- [x] Outermost parens should not be rendered.
- [x] Proof sometimes gets green/checkmark even if not complete
- [x] In the submission review, the proofs aren't displayed, only the endsequent is
- [x] If it's easily possible it would be useful to expose the JSON in the submission review so I can cop a student's proof to discuss it with them or help them along (if the exam option is available, which I haven't checked)
- [x] The end-sequent is not editable, which is ok. Can you turn off Ctrl+Shift+Enter when you're in it? Otherwise you can add a child node to the endsequent, which is then not editable, and there doesn't seem to be another way to recover when that happens, either.

**Comment by rzach** [comment]
For issue 3, eg:
```
{"ident":49,"label":"((A ∧ B) → C) ⊢ ((A → C) ∨ (B → C))","rule":"CR","forest":[{"ident":55,"label":"((A ∧ B) → C) ⊢ ((A → C) ∨ (B → C)), ((A → C) ∨ (B → C))","rule":"\\/R","forest":[{"ident":56,"label":"((A ∧ B) → C) ⊢ ((A → C) ∨ (B → C)), (B → C)","rule":"XR","forest":[{"ident":57,"label":"((A ∧ B) → C) ⊢ (B → C), ((A → C) ∨ (B → C))","rule":"\\/R","forest":[{"ident":72,"label":"((A ∧ B) → C) ⊢ (B → C), (A → C)","rule":"->R","forest":[{"ident":73,"label":"A, ((A ∧ B) → C) ⊢ (B → C), C","rule":"XR","forest":[{"ident":74,"label":"A, ((A ∧ B) → C) ⊢ C, (B → C)","rule":"->R","forest":[{"ident":75,"label":"B, A, ((A ∧ B) → C) ⊢ C, C","rule":"XL","forest":[{"ident":76,"label":"((A ∧ B) → C), B, A ⊢ C, C","rule":"->L","forest":[{"ident":77,"label":"C, B, A ⊢ C, C","rule":"","forest":[]},{"ident":78,"label":"B, A ⊢ C, C, (A ∧ B)","rule":"","forest":[]}]}]}]}]}]}]}]}]}]}
```
![Screenshot from 2020-09-16 18-00-39](https://user-images.githubusercontent.com/3122348/93404120-9803b380-f846-11ea-9d4f-24dfccbd2cc9.png)

**Comment by rzach** [comment]
Not sure what exactly you have to do to make that happen. I think it happens when you add a parent node at the top, then a sibling node, then undo.

**Comment by gleachkr** [comment]
I think I've got a lead on 3. The sequent checker thinks that the proof is correct whenever no node is marked internally as wrong.

But, certain ways of editing the proof (notably, pasting an incomplete proof into the box which justifies the root - probably some cut and paste edits, or undo edits of the kind you've tested) don't trigger the mechanism that checks the inferences within the edited portion of the proof (so you'll notice that if you paste the proof above in, as above, not every node has feedback available). With no mark one way or the other, the proofchecker lets it slide. I'll see about adding some extra safety for these cases. Thanks for the catch!

**Comment by gleachkr** [comment]
For 3, the fix is to basically detect missing information that might be caused by a nonlocal  edit, and in that case, to check the entire tableau rather than just checking edited lines. This fixes the cases I was able to find, but if you notice anything else please let me know.

**Comment by gleachkr** [comment]
The last two parts should be fixed by 5de5eb6187d117eb7f2bcb80a61edc7d5831127d. Deploying now, should be live in 5 minutes or so.

**Comment by rzach** [comment]
Was about to close when I ran into another issue ;)

**Comment by gleachkr** [comment]
OK, blocked the creation of a parent node in this case, and also added warnings when you try to do that or when you try to delete the root node.

**Comment by rzach** [comment]
Great! I got confused with "child" and "parent".  I tend to think of the premises as the parents (like in a genealogy tree), but you think of it as the parent/children in a graph-theory tree.  I'll just update my instructions unless you think you want to switch terminology.

**Comment by gleachkr** [comment]
Ah, right! Hm. Maybe better to stick with the graph-theory terminology? That's how all the functions are named in ProofJS.

**Comment by gleachkr** [comment]
Ready to close?

**Comment by rzach** [comment]
Yeah!
