### ISSUE TITLE
Deprecate guides option, make guides="..." do everything

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#188]
If I put `option="guides"` into a fitch `.ProofChecker`  problem, it doesn't seem to do anything different than when I leave it out.
If I put `guides="fitch"` I get the scope line overlay, even if I leave out the `guides` option.

Is `option="guides"` on its own supposed to do something?

**Comment by gleachkr** [comment]
It should have the same effect as `guides="montague"`. It's possible that you're not seeing the overlay because both of these are keyed in the `Show` keyword - the guide lines ought to occur beneath that word.

**Comment by rzach** [comment]
Ah ok so for Fitch proves, `option="guides"` doesn't do anything.  Could it?  I see students often having trouble with lining up formulas in subproofs even with `autoindent`. But the underlined assumption are maybe a bit busy. So just a line whenever the indentation goes up?

**Comment by gleachkr** [comment]
I wonder about removing `options="guides"` option from the documentation (treating it as deprecated), and adding a `guides="indent"` for the indent guides without underlining the assumptions? 

I think `option="guides"` is really only there right now for historical reasons, and it might be clearer to have all of the mutually incompatible ways of configuring guides keyed in under a single setting.

**Comment by rzach** [comment]
I concur!
