### ISSUE TITLE
review and assign partial credit

### ISSUE THREAD

**Issue by loighic** [Carnap/Carnap#189]
Did something happen to the 'review and assign partial credit' page?

(1) Toggling between "All Problems" and "Needs Review" doesn't, as far as I can tell, change anything. 

(2) And then, whether it's on "All Problems" or "Needs Review", some correct, automatically graded problems just have "Autograded, no data for review" and some correct, automatically graded problems show the problem. 

Since I can see the submission score, I can still relatively efficiently go through the problems that need to be checked. It was nice, though, to have a page of only the problems with mistakes that needed to be checked---and I think that was what I was getting up until yesterday.

**Comment by gleachkr** [comment]
Thanks! Yep, the move to a CDN caused the toggle for "All Problems"/"Needs Review" to break. This should now be fixed.

I think (2) may be expected behavior - some problem types (notably, truth tables) don't yet save correct answers, while others (e.g., derivations) do. But if that's not it, please let me know.

**Comment by loighic** [comment]
Ok, cool. (1) seems to be fixed. Thanks.

I'm getting (2) for truth tables, as shown in the screen shot. Although this, of course, is when "All Problems" is selected, which I don't normally view.

![auto-graded--tt](https://user-images.githubusercontent.com/54258105/95482150-6c5e7f80-0953-11eb-9975-fa144670e88c.png)

**Comment by gleachkr** [comment]
OK, yep, that tracks. The truthtable data may or may not appear, depending on whether the student just hit submit, or checked the table before submitting, or submitted a counterexample as a solution (this is a bit confusing, sorry!). Part of the reason for the trouble is that I haven't yet written something that usefully displays student-submitted counterexamples. There's a tracking issue here: https://github.com/Carnap/Carnap/issues/98, which I'll update with the current state of play.

**Comment by loighic** [comment]
Ah, gotcha. Thanks.
