### ISSUE TITLE
CounterModeler notation: '0' and labels

### ISSUE THREAD

**Issue by news4wombats** [Carnap/Carnap#194]
Carnap has labels like
  Domain:
  P(_):
  R(_,_):
  c:
but this doesn't match the way models are labeled in forall x. It would be nice if the labels could be
  UD =
  extension(P) =
  extension(R) =
  referent(c) =
instead.

**Comment by news4wombats** [comment]
A related issue that came up today: One of my students was confused by the zeroes which appears as the default Domain and referents. They seemed to be mixing it up with the 0 meaning falsity (in forall x's truth tables) and the 0 meaning non-satisfaction (when thinking about the semantics). When I work examples with numbers, I tend to use (e.g) {6,7} instead of {0,1} so as to avoid this miscue.

It's not a big deal, but it would be nice either if there were a way to have Carnap not prepopulate the model or if populating it with 0s could be overridden.

**Comment by news4wombats** [comment]
The second post seemed like a related issue, but maybe it should have been posted separately rather than as a followup. I'm uncertain of github etiquette.

**Comment by gleachkr** [comment]
No worries, I think it makes sense to group these. I'll update the title to make it a little clearer.

**Comment by rzach** [comment]
FYI You can now provide countermodeler inputs in the source as a "given", e.g.

    ~~~{.CounterModeler .Simple }
    P1 Ax Px
    |Domain:6,7
    ~~~

now does what you mention in the related issue.

**Comment by gleachkr** [comment]
I've finished a draft of this - it should be up on the server in a few minutes. The alternate display style can be set by adding `forallxStyle` to the options string, as in:

    ```{.CounterModeler .Validity options="forallxStyle strictGivens"}
    1.2 F(f(a)):|-:Ex(F(x))
    ```

Which produces:

![20210414_13h30m45s_grim](https://user-images.githubusercontent.com/6383381/114761099-b1f66d80-9d25-11eb-8612-2cb2170fd770.png)

I used `extension(f)` for function symbols, and `truth-value(P)` for propositional letters, I hope that's OK.

**Comment by news4wombats** [comment]
That looks great.

Quantified Logic as defined in (original) forall x doesn't include
functions or propositional letters, so it doesn't really matter how those
are labelled.

Thanks very much!

**Comment by gleachkr** [comment]
Great! If anything needs to be changed, feel free to reopen this issue.
