### ISSUE TITLE
Improve FOL equivalence check

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#20]
FOL translation checker does not recognize `Ax (Ax /\ Bx)` as equivalent to `Ax Ax /\ Ax Bx` (and similarly for `Ex` and `\/`.  I suspect the "standard rules of passage" mentioned in https://carnap.io/shared/gleachkr@gmail.com/carnap-translation.pandoc#fn1 don't include 

- `Ax (Ax & Bx) -> Ax Ax & Ax Bx`
- `Ex(Ax \/ Bx) -> Ex Ax \/ Ex Bx`

If they do then something's going wrong in these test cases:

https://carnap.io/shared/rzach@ucalgary.ca/test%20case%20issue.md

**Comment by gleachkr** [comment]
Thanks! It was indeed as you suspected. I've added the variable-merging rules you mention, along with `∀xFx→∃xGx` to `∃x(Fx→Gx)`. This fixes all the examples you sent except for 7 and 8. I think those two might contain a typo - I suspect that an ∧ got replaced by an ∨.

**Comment by rzach** [comment]
Indeed, there was a typo in 7 & 8. It's working now. 
Did you also add ∃xFx→∀xGx to ∀x(Fx→Gx)?
(Probably a different issue but the partial solution `|Ax(P(x) -> (Q(x) /\ R(x)))` gets put into the text input box with an escaped `>`, ie as `Ax(P(x) -&gt; (Q(x) /\ R(x)))`. Shall I report that issue separately?)

**Comment by gleachkr** [comment]
Great! Probably best to report the escaping issue separately. Should be an easy fix, but might take a minute to track down the origin.

I didn't add ∃xFx→∀xGx to ∀x(Fx→Gx). The way the check works at the moment, it can only use strict equivalences as rewrites, unfortunately. It might be possible to write a variant that also bakes in some other rewrites to catch implied sentences as well as equivalent ones though, to have a proof system incorporating an "FOL rewrite" tactic...

**Comment by rzach** [comment]
Oh yeah, of course, those aren't equivalent.

**Comment by gleachkr** [comment]
closed by 33aff1fe7e59f61b370ffffb0a736392b94fa98a
