### ISSUE TITLE
rule HS in ForallxSLplus

### ISSUE THREAD

**Issue by news4wombats** [Carnap/Carnap#200]
In the proof system the original version of forallx, the hypothetical syllogism rule is abbreviated HS.
In the Carnap system ForallxSLplus, the rule displays correctly as HS in the depiction of the proof but must be entered as HYP in the text box. The parser doesn't recognize the rule if it's entered as HS.

**Comment by gleachkr** [comment]
Thanks for the report. This should now be fixed by 4a5b2837e85d9252ed228033582e93bf07a4d2cc.

**Comment by news4wombats** [comment]
Thanks!
