### ISSUE TITLE
expressions with free variables allowed in proofs

### ISSUE THREAD

**Issue by news4wombats** [Carnap/Carnap#206]
The proof systems ForallxQL and ForallxQLPlus allows expressions with free variables; e.g. one can infer Px from AxPx.
In the Forallx proof system, however, every line of a proof must be a sentence and sentences cannot have free variables.

I suspect that the same holds for the Forallx Calgary system, but I haven't confirmed that.

**Comment by gleachkr** [comment]
Thanks! I've deployed an extra check at the parsing level for ForallxQL/ForallxQLPlus, so that formulas with free variables will be disallowed.
