### ISSUE TITLE
Can't update .css file

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#207]
I have a css file as a shared file:
https://carnap.io/shared/rzach@ucalgary.ca/wideinput.css
When I try to update it, the file stays the same (no error).

**Comment by gleachkr** [comment]
Odd. The file on disk shows that it was updated today, and has an extra css for countermodelers (is that what you added?). So - if that was the change you made - it looks like everything was uploaded correctly, but isn't being served correctly.

**Comment by rzach** [comment]
Yes, that's what I did. Closing browse, reload, shift-reload didn't work, so I don't think it's a caching issue.

**Comment by gleachkr** [comment]
OK, I think I've got it. I forgot that on the production server, when a file with one of a few specific mimetypes (including `text/css`) is is served, it's gzipped before being served, and the zipped file is cached (to avoid needing to rezip with every request). Now that we're using a CDN for our big static files, the on-server cache isn't doing much work, so I think it's OK to just gzip with each file request. I'll try to fix soon.

**Comment by gleachkr** [comment]
Should now be fixed. We're now gzipping on every request, but all the heavy requests should be cached by the CDN, so I don't think this will be a performance problem. For folks who want to run a server without a CDN, it's possible to place a `.gz` suffixed file in the same directory as the served file, and the suffixed file will be served instead (should probably note this in the docs somewhere).

**Comment by gleachkr** [comment]
Should now be fixed. If not, please reopen!
