### ISSUE TITLE
> in partial solutions of translation exercises are escaped

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#21]
A `>` in a partial solution of a translation exercise displays as `&gt;` in the text input box, eg:
```
~~~{.Translate .FOL system="thomasBolducAndZachFOL2019"}
4 Ax(P(x) -> Q(x)): All Ps are Qs
|Ax(x is a P -> x is a Q)
~~~
```
displays as `Ax(x is a P -&gt; x is a Q)`

**Comment by gleachkr** [comment]
Should be closed by 6d099404cf5c0ab779388922a685cde4adf43f9c
