### ISSUE TITLE
Removing the ⊤ that represents the empty antecedent to a sequent

### ISSUE THREAD

**Issue by loighic** [Carnap/Carnap#211]
Hi, can the symbol that is displayed before the turnstile when no premises are given be removed from AllenSL and AllenSLPlus? Unfortunately, I think that the symbol will confuse my online students. They won't be getting to proofs of theorems until March, however, and so this isn't too pressing. Thanks.

**Comment by gleachkr** [comment]
Sure thing. You should see the change with the next server update.

**Comment by loighic** [comment]
Ok, cool. Thanks.
