### ISSUE TITLE
More pandoc extensions

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#214]
I'm not sure what the trade-offs are for enabling more pandoc extensions. Since I use pandoc  Two extensions that would be useful for me:

-    `startnum`: so a numbered list starts with the first number given, rather than always starting with 1
-   `fenced_divs`: enabling pandoc's simpler syntax for adding `div` elements (which I find I am using a lot now, with custom css and javascript)

I guess more generally, since I use pandoc regularly for other stuff, I get tripped up when the extensions supported by Carnap are different from the default pandoc markdown extensions.

**Comment by gleachkr** [comment]
There might be some sort of microscopic hit to efficiency, but I think the trade-offs are pretty minimal. And these seem like sensible extensions to have. So, I will switch them on.
