### ISSUE TITLE
Sort assignments on user page by due date

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap#215]
Right now they're sorted by creation time, which can be a headache if you're creating a large number of assignments.

**Comment by gleachkr** [comment]
closed by 7f6b99e8adc3764f528daf53d39c5cf55827c914.

**Comment by rzach** [comment]
Can we sort them by due date also on the instructor page?

**Comment by gleachkr** [comment]
Good idea. I added this along with some sorting toggles for reverse sort and sort by name. Currently deploying.
