### ISSUE TITLE
Rules for <-> for LK & ND

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#221]
I can see running into some difficulty doing actual proofs in LK and ND in the OLP languages with <-> defined as -> & <-. It would be nice to have direct rules for <->.

For NK/NJ they are:
Rule | Premise Sequents | Conclusion Sequent
-- | -- | --
<->I | Γ, φ ⊢ ψ ; Δ, φ ⊢ ψ | Γ,Δ ⊢ φ <-> ψ
<->E | Γ ⊢ φ <-> ψ ; Δ ⊢ φ | Γ,Δ ⊢ ψ
<->E | Γ ⊢ φ <-> ψ ; Δ ⊢ ψ | Γ,Δ ⊢ φ

For LK/LJ they are:

Rule | Premise Sequents | Conclusion Sequent
-- | -- | --
<->R | Γ, φ ⊢ Δ,ψ ; Γ, φ ⊢ Δ,ψ | Γ ⊢ Δ, φ <-> ψ
<->L | Γ, φ, ψ ⊢ Δ ; Γ ⊢ Δ,φ | φ <-> ψ, Γ ⊢ Δ
<->L | Γ, φ, ψ ⊢ Δ ; Γ ⊢ Δ,ψ | φ <-> ψ, Γ ⊢ Δ

**Comment by gleachkr** [comment]
Should be ready to go! But I could use a little help with testing, if you have time (the LK changes required rearranging things a little bit, since OpenLogicLK/LJ is no longer a notational variant on the Gentzen system).

**Comment by rzach** [comment]
Looks good. Of course I gave you the wrong rules!  The <>L rules should be:

Rule | Premise Sequents | Conclusion Sequent
-- | -- | --
<->L | Γ, ψ ⊢ Δ ; Γ ⊢ Δ,φ | φ <-> ψ, Γ ⊢ Δ
<->L | Γ, φ ⊢ Δ ; Γ ⊢ Δ,ψ | φ <-> ψ, Γ ⊢ Δ

(Delete one fmla from left premise antecedent: φ <-> ψ is false if ψ is false and φ is true, or the other way round.)

**Comment by gleachkr** [comment]
Got it! Should now be updated.

**Comment by rzach** [comment]
See https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20LK.md 7 examples down (Iff2). I think this proof is correct but it doesn't turn green.  There seems to be an issue where Carnap doesn't recognize ¬L as a legal rule name. But if you change it to ~L it still doesn't check.

**Comment by gleachkr** [comment]
I think it's a combination of two things. ¬L isn't getting recognized as a rule name, and the proof-check isn't rerunning globally after a parsing failure is resolved. If you click around and use the arrow keys, you can trigger parsing in the blocked parts and eventually get the proof to check out.

The sequent calculus widget tries to check locally (just looking at adjacent lines) rather than globally, since you can get away with this in the sequent calculus, and it's more efficient. But the fact that a parsing failure gets propogated through the whole proof means that it ought to recheck everything in downstream when a parsing failure is resolved.

Fixing the rule-name issue should be pretty easy. I'll take a look and try to figure out what to do about the second issue.

**Comment by rzach** [comment]
Second exercise in https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20ND.md
Doesn't parse with ↔ but parses fine with `<->`

**Comment by gleachkr** [comment]
So, something weird is going on with the ↔ characters showing up in that proof.

It looks like they consist of the character with hex code `e2 86 94`, which is the bicondiitonal in utf-8  plus an invisible combining character with the hex code `ef b8 8e`, ~which is, via utf-8, somewhere in the private use area of unicode. :exploding_head:~

What's the character entry method that's giving you that biconditional?

If you copy paste the biconditional that appears in the goal sequent above the proof tree throughout the proof, then the proof seems to check out.

**Comment by rzach** [comment]
Copy and paste from https://www.w3schools.com/charsets/ref_utf_arrows.asp
I tried replacing them with ↔ copy/pasted from the Carnap page itself (the ↔ in the sequent to be proved)

**Comment by rzach** [comment]
I mean I tried what you suggested, but it didn't work for me. (It works if I do it in Carnap by hand, but nothing I do in the file itself seems to work. Maybe it's Linux?)

**Comment by gleachkr** [comment]
Maybe? Or the editor it's getting pasted into? I'm testing the byte sequences for the character using vim, if that's helpful at all, `g8` gives you the byte sequence for the character under the cursor. It gives `e2 86 94` for the usual biconditional, and `e2 b8 94 + e2 b8 8e` for the biconditionals appearing on the page there.

**Comment by gleachkr** [comment]
I don't see the extra character when I copy from w3schools...

**Comment by gleachkr** [comment]
The bytes in the underlying file look right. Ugh.

**Comment by rzach** [comment]
I looks like that second code is variation selector 15, and according to https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block) it means "display the preceding symbols as text rather than an emoji". I'm guessing someone (the OS, Firefox, VS code) is trying to be helpful.

**Comment by rzach** [comment]
Oh, if its correct in the file then it's Carnap that's converting it somewhere? By why doesn't it break in the usual Fitch checkers then?

**Comment by gleachkr** [comment]
I'm not sure. I certainly didn't set it up to do something like this. Maybe it's the web browser that's trying to be helpful?

**Comment by gleachkr** [comment]
It looks like the biconditionals that appear in the text paragraph above the problem also have the combining character.

**Comment by rzach** [comment]
Oh, the script gives it the glyph and my Firefox turns it into glyph + "display as text"? But then it's in the textbox as two UTF8 chars and this breaks it?  I provided the premise in https://carnap.io/shared/rzach@ucalgary.ca/More%20Practice%20Problems%20IV.md IVb.11 as a given with the ↔ character and that doesn't make a problem with the parser there....

**Comment by rzach** [comment]
> It looks like the biconditionals that appear in the text paragraph above the problem also have the combining character.

The ones between A and B are made by $A \leftrightarrow B$. Do they have it too?

**Comment by gleachkr** [comment]
My best guess is that the web browser might do it contextually - maybe not when the character shows up directly in a div (as it does when it's displayed as a goal), but when it shows up in an element that the browser thinks of as primarily text, like a `<p>` or an `<input>`.

**Comment by gleachkr** [comment]
> > It looks like the biconditionals that appear in the text paragraph above the problem also have the combining character.
> 
> The ones between A and B are made by $A \leftrightarrow B$. Do they have it too?

They do, yep. And that's just pandoc, not carnap.

**Comment by gleachkr** [comment]
Simplest solution might be to add the variant utf-8 biconditional to the parser, since it seems likely that this is something some browsers do systematically, rather than a one-off glitch of some kind.

**Comment by gleachkr** [comment]
Hrm. OK, actually, pandoc produces the variant bytes outside the context of a web browser. If you 

```
echo "$\leftrightarrow$" | pandoc > out.html
```

You get the variant.

**Comment by gleachkr** [comment]
OK, I think I need to take a break. But, adding the alternate to the parser should work - OK if I do that tomorrow?

**Comment by rzach** [comment]
Yeah, no rush. After all, typing `<->` is a good workaround.
(Since it doesn't seem to cause problems in the Proof Checker where everything is in an <input>, does it mean there must be something in ProofJS that breaks this?)

**Comment by gleachkr** [comment]
Looks like an explicit choice in pandoc:

https://github.com/jgm/pandoc/issues/5469

**Comment by gleachkr** [comment]
OK, I think the extra bytes are coming from the patch that was inserted to resolve that pandoc issue. As part of the pandoc filter that generates the exercise, the json gets passed through the relevant part of pandoc's html writer. I've rerouted, and it looks like the combining character is no longer being added. Currently deploying...

**Comment by gleachkr** [comment]
Seems to be fixed!

**Comment by gleachkr** [comment]
Ok to close?

**Comment by rzach** [comment]
Thanks!

**Comment by rzach** [comment]
Ooops discovered two small things: NK does not like the `→I` and `→E` rules (I think it's looking for horseshoes instead) and LK doesn't like `>L` and `>R` even though `>` is ok for →.

**Comment by gleachkr** [comment]
OK, should be fixed!

**Comment by rzach** [comment]
I think not (anymore): https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20ND.md
(Also noticed that `~E` is accepted for the OLP systems for ⊥/φ but it should only take `X`)

**Comment by gleachkr** [comment]
Thanks, once again - OK, those bugs are now squished.

**Comment by rzach** [comment]
See https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20ND.md ex 9.7: it doesn't like `∧E` and `∧Elim` and same with I, Intro

**Comment by rzach** [comment]
LK also doesn't like `>L` and `>R`

**Comment by gleachkr** [comment]
Also squished.

**Comment by rzach** [comment]
Wonderful!
