### ISSUE TITLE
Correct proof not recognized

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#222]
In https://carnap.io/shared/rzach@ucalgary.ca/279%20Problem%20Set%203.md problem 10, Carnap gives me +'s on every line and the sequent in the tooltip on the last line is identical to the sequent to be proved. But it doesn't turn green. Here's what I put in:
![Screenshot from 2021-01-26 08-11-48](https://user-images.githubusercontent.com/3122348/105863777-795cb880-5fae-11eb-8530-15bba833d344.png)

```
    (A \/ (B -> C)) /\ B :AS
    A \/ (B -> C) :/\E 1
    B :/\E1
        A :AS
        A /\ A :/\I 4,4
        C \/ (A /\ A):\/I 5
    --
        B -> C :AS
        C :->E 3,8
        C \/ (A /\ A):\/I 9
    C \/ (A /\ A):\/E 2,4-6,8-10
 ((A ∨ (B → C)) ∧ B) → (C ∨ (A ∧ A)) :->I 1-11
```

**Comment by gleachkr** [comment]
I think there might be a leading space character on the final line---is this what's causing the trouble?

**Comment by rzach** [comment]
Indeed! Is there a way for the proof checker to catch that?  (Eg if the last line starts with a space, technically it should be assumed to be in a subproof but the checker, but no subproof at the same indentation level has been opened before. (The rendered version in fact has the last line with space on the same scope line as the subproof started by line 1). So Carnap should complain that the line does not match the indentation of an assumption line, or that as the first line of a subproof it must be justified by `:AS`.  I think there's already a bug somewhere that the interpretation of the subproof structure by the checker doesn't always match what's rendered.

**Comment by rzach** [comment]
Right it's issue #93
