### ISSUE TITLE
Corrupted proof display after unsuccessful submit

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#223]
If you click on the submit button for the exercise in #222 you get a "not yet finished" message and afterward the display looks like this:
![Screenshot from 2021-01-26 08-14-55](https://user-images.githubusercontent.com/3122348/105863997-b4f78280-5fae-11eb-9b9b-5ce7b81f20fc.png)
(In Firefox on Ubuntu)

**Comment by rzach** [comment]
(I guess what is happening is that the resize option expands the box as the proof grows, and the submit butto resets the box size to the original size). But then the resize option afterward seems to be deactivated or something, since chaning the proof doesn't fix it (expand the box)

**Comment by gleachkr** [comment]
Thanks. Appears to be browser-agnostic, I'll look into it.

**Comment by gleachkr** [comment]
Looks like it was introduced with the JavaScript API changes - the wrong div is getting targeted with the new "failure" event and css class, and the css class is clobbering something that should be there. Will fix.
