### ISSUE TITLE
Carnap shows all alternate versions of problem

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#225]
I have assigned

https://carnap.io/assignments/Calgary%20Phil%20279%20L01%20Winter%202021/279%20Challenge%20Problem%203%20B.md

It has 1 question, consisting of 8 alternate versions of a truth table. Carnap shows all 8 instead of randomly selecting one.

**Comment by gleachkr** [comment]
Rats, sorry about that. Side effect of a change that went up this afternoon. Should now be fixed.

**Comment by rzach** [comment]
Thanks for the quick fix!
