### ISSUE TITLE
Delete unused tags 

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#228]
It looks like tags stick around in the shared documents list even if no page with that tag is accessible.  I'm not sure if that's just because *I* don't have access to the file, or if the file is deleted.

- Tags should definitely be deleted if the last document using that tag is deleted.
- Harder to do: show user only tags on documents they have access to

**Comment by gleachkr** [comment]
I think it's the latter - tags depends on the underlying document in the DB, so when the last document with a certain type of tag is deleted, that tag should no longer exist. 

I'll see about screening the tags according to visible documents, rather than just dumping them all into the UI though!

**Comment by gleachkr** [comment]
Resolved by 54abf62c9d92261b49a21cb2cd46a03a533be0e5
