### ISSUE TITLE
Better site navigation

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#23]
- [x] After logging in, user should be taken to student homepage or instructor homepage, not front page
- [x] The logout link is at the bottom of the page, and only on some pages. Users expect it where the login link is otherwise displayed, ie, at the top right
- [x] Add a link to shared documents https://carnap.io/shared at the top of the page, at least for instructors

**Comment by gleachkr** [comment]
I've added a navigation dropdown that lets you log out and also access your instructor page and the shared documents page. Login should now redirect to your user or instructor home, depending. Changes aren't live yet, but will go up this afternoon.

**Comment by rzach** [comment]
Cool, thanks!
