### ISSUE TITLE
Documents API

### ISSUE THREAD

**Issue by gleachkr** [Carnap/Carnap#231]
This is an issue for tracking the MVP for the documents API described in #226.

We want these endpoints:

- [x] GET https://carnap.io/api/v1/instructor/:instructorIdent/documents
- [x] POST https://carnap.io/api/v1/instructor/:instructorIdent/documents
- [x] GET https://carnap.io/api/v1/instructor/:instructorIdent/documents/:documentId
- [x] ~PUT~ PATCH https://carnap.io/api/v1/instructor/:instructorIdent/documents/:documentId
- [x] GET https://carnap.io/api/v1/instructor/:instructorIdent/documents/:documentId/data
- [x] PUT https://carnap.io/api/v1/instructor/:instructorIdent/documents/:documentId/data

and

- [x] Documentation

Work is currently on rest-api branch.

**Comment by gleachkr** [comment]
I am now thinking that it makes the most sense to support only PATCH for individual document metadata.

1. This subsumes everything you'd want to do with PUT
2. It reduces the chances of accidentally "PUT"-ing your json to the wrong URL and clobbering your document
3. It's not clear why you'd ever want to entirely replace a document, retaining nothing but the databased ID.

**Comment by lf-** [comment]
WIP documentation is at https://carnap.io/srv/doc/api.md#document-api

**Comment by gleachkr** [comment]
Great, I filled in `POST` and `PATCH`. The python examples are great. I wonder about writing this so that we can fill in a couple of languages? I can do that later, if that's OK with you.

**Comment by lf-** [comment]
> Great, I filled in `POST` and `PATCH`. The python examples are great. I wonder about writing this so that we can fill in a couple of languages? I can do that later, if that's OK with you.

Sure! The Python examples are mostly just there to show the expected shape of the output more than to do anything terribly language specific. I'm going to be using typescript for the action anyway later, so it really was just whatever i could poke it with fastest.
