### ISSUE TITLE
negation sign in AllenSL

### ISSUE THREAD

**Issue by loighic** [Carnap/Carnap#232]
I'm not sure how it happened, but the negation sign in AllenSL and AllenSLPlus has changed from `¬` to `~`. Did someone else request the change? Having ¬ would be better for me since I have so many teaching materials (in particular, videos) with it. But if there is some reason why it changed, maybe I can live with it. 

My students recognize ~ as a negation sign (and use it for keyboard entry), and so this isn't pressing, in any case.

**Comment by gleachkr** [comment]
I think this was changed as part of #198 - I'm told this is what's in the Allen book but I don't actually have a copy myself. I think maybe it'd be better to stick with the book, but I'm not dogmatic if you strongly disagree (I could also create an AllenSL variant pretty easily if that'd help).

**Comment by loighic** [comment]
Ok, well, this could potentially create some problems for me, and it's also a little bit of a bigger issue than just the negation sign. But as long as no other changes get made to AllenSL (to make it more similar to the book), then we can wait until this summer to figure it out.

The current AllenSL follows the spirit of the Allen book, but deviates from the book in several places. (And so it is, in fact, just the system in my own version of _forall x_.) If you want to reserve AllenSL for the system in the book (and give the system that I need some other name), then I can make a draft of the .hs file for Allen's book---but maybe not until May. And, since we're already into the current semester, it wouldn't be that easy for me to use anything besides AllenSL right now.

(Sorry if this is creating more work than it should. It's been kind of winding journey from my pre-Carnap teaching to where I am now.)

**Comment by gleachkr** [comment]
That makes sense, thanks for the information. I think maybe then the thing to do is this:

1. Revert the changes to AllenSL from #198,
2. Create an JohnsonSL (or whatever title you'd like), as an alias for AllenSL, so that you can migrate to that name whenever would be convenient
3. Eventually, when it won't cause breakage, create something more like the original Allen system, and redirect AllenSL to that.

Does that seem like an OK plan?

**Comment by loighic** [comment]
Ok, cool. Sounds good. Thanks.

**Comment by gleachkr** [comment]
OK, items 1 and 2 are implemented, we can come back to 3 at some future date.

**Comment by rzach** [comment]
Just FYI I've documented the `JohnsonSL` system https://carnap.io/srv/doc/forallx-msu.md I see there's also a `JohnsonSLPlus` system but I don't think that's in the book so I left it out.

**Comment by loighic** [comment]
Graham, cool. Thanks. It's looks like johnsonSL doesn't have the playground feature---which I would use, although I don't need it this spring.

Richard, thanks. And that's right about the SLPlus rules.

**Comment by gleachkr** [comment]
Oops! OK, playgrounds for johnsonSL are now implemented.
