### ISSUE TITLE
Can't remove due dates

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#234]
I don't have this problem myself, but my TA reports (and I've seen it on her screen) that the calendar widget for due dates does not have an x button to remove the date (on Chrome and Edge on Windows).

**Comment by gleachkr** [comment]
I *think* what is happening here is that jQueryUI is conditionally loading its datepicker, and getting out of the way of browsers with built-in datepickers.

Firefox has a built-in datepicker with the nice "clear date" button, and I'm guessing the other browsers don't have this.

It should work to just select the date and delete it using the keyboard - does that work OK?

**Comment by rzach** [comment]
IIRC she only gets a date picker, and can't edit the date string itself. I'll investigate and report back. Not terribly hard to work around for the moment.

**Comment by gleachkr** [comment]
Ah, OK. Screenshot might be good, to see if this is the [jQuery UI datepicker](https://jqueryui.com/datepicker/)

**Comment by rzach** [comment]
This is the date picker in Chrome. It is possible to just delete the date string. So no need to fix this; you can close if you want to.

![datepickerchrome](https://user-images.githubusercontent.com/3122348/107854026-73e8d600-6dd6-11eb-8789-c7eea3361ea1.png)
