### ISSUE TITLE
init=now gives feedback even when feedback="none" 

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#241]
The first proof on https://carnap.io/shared/rzach@ucalgary.ca/279%20Tutorial%20Worksheet%207%20copy.md
has `feedback="none"` and `init="now"` set. There is feedback even though there shouldn't be. The rendered proof is not updated when I type.

The second proof has `feedback="manual"` and `init="now"`. Feedback is there; it should only be given once you press "check".

The third has `feedback="syntaxonly"` and `init="now"` and behaves as expected.

The next three don't have `init="now"`.

The first one hides feedback as expected, but doesn't render the proof.

The second renders the proof but shows feedback on loading, which it shouldn't.

The third behaves as expected.

So: `init="now"` triggers a check even when `feedback="none"`  or `feedback="manual"`

"option=`render`" is not honored when `feedback="none"`

**Comment by gleachkr** [comment]
When feedback is manual, do you think it would make more sense to re-render the proof on every keypress, or to only re-render when button is clicked?

**Comment by rzach** [comment]
It's not computationally intensive to render, right?  Then I'd say every key press.  (I tend to think of the render option as just a way to make them see something that's closer to the textbook, not as a way to check correctness, which it doesn't.
