### ISSUE TITLE
What's Ctrl+? on Mac?

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#244]
The Ctrl+? key combo to display the JSON panel for `.TreeDeduction`s doesn't seem to work on Mac, nor does Command+?. What's the right combo?

**Comment by gleachkr** [comment]
I just did a test with an old mac, and I think that the ctrl key on a mac causes the shift key to be ignored when it comes determining the key code of the keyboard event, so to the browser, the `?` looks like a `/` (you might be able to confirm this is the issue at keycode.info). I'll try a simple workaround, also catching `/` when `Ctrl` and `Shift` are active.

**Comment by gleachkr** [comment]
Seems to do the trick!

**Comment by gleachkr** [comment]
Closed by 5b730b06a7a31605b4a1ed69cc13a988da8d2794

**Comment by rzach** [comment]
Deployed?

**Comment by gleachkr** [comment]
Should be, I was able to use Ctrl+? while testing on a mac.

**Comment by rzach** [comment]
Ok my student (who has the Mac) says it works now!
