### ISSUE TITLE
Review/manual grading of proofs involving \/ broken

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#247]
I assigned a .TreeDeduction problem which was auto-graded as correct but when I review the submission Carnap shows me an incorrect derivation -- there seems to be a problem with not escaping `\` in `\/`.
![Screenshot from 2021-03-20 11-11-53](https://user-images.githubusercontent.com/3122348/111879138-62629300-896d-11eb-84b9-9847a2050630.png)

**Comment by gleachkr** [comment]
Shoot, thanks. I'll take a look ASAP.

**Comment by gleachkr** [comment]
[As you suspected](https://xkcd.com/1638/). I just deployed a fix, so the derivations should display properly soon. If you happen to want to use a formal language that includes carriage returns, that should work now too.

**Comment by rzach** [comment]
LOL yes maybe we should include Frege's notation.
