### ISSUE TITLE
Odd parser issue in .TreeDeduction

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#250]
See 
https://carnap.io/shared/rzach@ucalgary.ca/379%20Basic%20Problem%206%20copy.md
The last inference (all the way on the right) is red and gives a parser error. But I can't tell why.

Also, the parser error should preferably be displayed at the formula that gives the error.

**Comment by gleachkr** [comment]
I think there's an extra space character in front of the formula in the root node. The parser should be able to handle that, though, I'll make a fix.

**Comment by rzach** [comment]
Shouldn't it turn the endformula red instead of the inference though?

**Comment by gleachkr** [comment]
Yes, that's a bit of UI fail. The trouble is that the internal model of the tree is just a tree, with each node decorated by a formula, an inference label, and possibly an error message. The error message is just a string, so it doesn't really have enough internal structure so say whether it should be associated with the formula or the inference label. Fixing this will take some changes to ProofJS, and probably corresponding changes on the Carnap side. As a short-term remedy, I think it would be possible to have the error message indicate whether the parse error is coming from the formula or the inference label.

**Comment by rzach** [comment]
Do you want a separate issue for it? 

One thing that would help a lot I think is if the error could be displayed only where it is, and where it percolates down you just show a generic error message (like the "waiting for parsing to be completed" greyed out formulas if there is a parser error somewhere else). This would indicate that checking on a node isn't done because a higher node failed a check)

**Comment by gleachkr** [comment]
Maybe we can add these to #220, and put a checklist there?

**Comment by gleachkr** [comment]
Parser tweak should now be live

**Comment by rzach** [comment]
Thanks! Also done re: #220
