### ISSUE TITLE
Derivations with partially filled solutions not checked on load

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#256]
When a derivation has a partial (or complete) solution, Carnap doesn't check the solution on page load, and so doesn't show any error messages, or any indication that the derivation is complete. To trigger Carnap, one must click on the derivation and add a new blank line. It seems to me like it ought to check the solution when it loads the page?

**Comment by gleachkr** [comment]
Maybe the init option would help here? 

https://carnap.io/srv/doc/derivations.md#initialization

**Comment by dsanson** [comment]
Nice! Didn't know that existed.
