### ISSUE TITLE
Email instructors always goes to GLK

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#262]
The "email instructors" link on the administration page goes to gleachkr@gmail.com with bcc's to registered instructors; it should go to the email address of the site admin.

(There are some other instances of this, perhaps the mailto: URLs for reporting errors etc should all be configurable.)

**Comment by lf-** [comment]
I want to fix this in my planned runtime config feature, because it's not necessarily the case that we want all emails of that sort to go to the instance admin as there may be multiple, or their Gmail is the wrong address to send it to. I'll be able to get started on it after the 25th.

**Comment by gleachkr** [comment]
With #269 merged, I think this can now be closed - instance admin email is now configurable from the admin page.
