### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#263]
Following the instructions in the README, when I do
```
$ nix-env -iA cachix -f https://cachix.org/api/v1/install
$ cachix use carnap
$ nix-build -j4 -A client -o client-out
```
it eventually craps out and says
```
Preprocessing executable 'AllActions' for Carnap-GHCJS-0.1.0.0..
Building executable 'AllActions' for Carnap-GHCJS-0.1.0.0..
[1 of 1] Compiling Main             ( AllActions/Main.hs, dist/build/AllActions/AllActions-tmp/Main.js_o )
Linking dist/build/AllActions/AllActions.jsexe (Main)
/nix/store/n4qv0ad1rg8rafppb4dh59n080m94bxy-stdenv-linux/setup: line 1300: 490128 Killed                  ./Setup build
builder for '/nix/store/9cj1sr2zhyb5nsl308llvmkhdfqaaf8c-Carnap-GHCJS-0.1.0.0.drv' failed with exit code 137
error: build of '/nix/store/9cj1sr2zhyb5nsl308llvmkhdfqaaf8c-Carnap-GHCJS-0.1.0.0.drv' failed
```
This worked yesterday; I re-did everything (including installing nix) from scratch to test something, and now this.

**Comment by gleachkr** [comment]
I think that might be an out of memory error. Can you watch memory usage while you're building? Is there some reason why there might be less memory available for the build?

**Comment by lf-** [comment]
That's an out of memory error. Our ghcjs side is absolutely cursed and in the process of generating a 45MB blob of JavaScript, or several, it uses about 12GB of memory. We do need to fix this.

**Comment by lf-** [comment]
I forget if it ended up getting merged, but I wrote a bodge that uses a prebuilt ghcjs front end. I'll go looking.

**Comment by rzach** [comment]
I closed Zoom and Firefox and it made it through; thanks!

**Comment by lf-** [comment]
> I forget if it ended up getting merged, but I wrote a bodge that uses a prebuilt ghcjs front end. I'll go looking.

It did not get merged. It's probably some branch I forgot about on the UBC fork. I should either resurrect it or put in the like week of work to figure out why we have this ghcjs problem to begin with, but I currently have summer finals coming up.
