### ISSUE TITLE
Another build problem

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#264]
Hm, running into another issue I didn't have yesterday:
```
[nix-shell:~/src/Carnap]$ make build-ghc
make[1]: Entering directory '/home/zach/src/Carnap'
cabal new-build -f dev all
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - Carnap-Server-0.0.0 (lib) (first run)
 - Carnap-Server-0.0.0 (exe:Carnap-Server) (first run)
Preprocessing library for Carnap-Server-0.0.0..
Building library for Carnap-Server-0.0.0..
[27 of 46] Compiling Handler.Serve    ( Handler/Serve.hs, /home/zach/src/Carnap/dist-newstyle/build/x86_64-linux/ghc-8.8.4/Carnap-Server-0.0.0/build/Handler/Serve.o )

Handler/Serve.hs:56:47: error:
    Variable not in scope: ghcjs_allactions_lib_js :: Route Static
   |
56 |                           addScript $ StaticR ghcjs_allactions_lib_js
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^

Handler/Serve.hs:57:47: error:
    Variable not in scope: ghcjs_allactions_out_js :: Route Static
   |
57 |                           addScript $ StaticR ghcjs_allactions_out_js
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^

Handler/Serve.hs:66:47: error:
    Variable not in scope: ghcjs_allactions_runmain_js :: Route Static
   |
66 |                           addScript $ StaticR ghcjs_allactions_runmain_js
   |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build Carnap-Server-0.0.0 (which is required by
exe:Carnap-Server from Carnap-Server-0.0.0).

make[1]: *** [Makefile:27: build-ghc] Error 1
make[1]: Leaving directory '/home/zach/src/Carnap'
```
It went away after I said `cabal new-clean -s` but I thought I'd report it just in case.

**Comment by gleachkr** [comment]
That one looks like it might be a result of `Settings/StaticFiles.hs` getting compiled at a time when the ghcjs files weren't available. That file has some template code in it that generates haskell identifiers for all of the files in the static directory, ensuring that they exist at build time. The new-clean probably forced `StaticFiles.hs` to recompile, and properly define all the `ghcjs_*`.

**Comment by lf-** [comment]
> That one looks like it might be a result of `Settings/StaticFiles.hs` getting compiled at a time when the ghcjs files weren't available. That file has some template code in it that generates haskell identifiers for all of the files in the static directory, ensuring that they exist at build time. The new-clean probably forced `StaticFiles.hs` to recompile, and properly define all the `ghcjs_*`.

That's definitely what caused it last time it happened to me. I believe I've fixed it before by checking the files were present then deleting dist-newstyle and rebuilding

**Comment by rzach** [comment]
What I was doing was trying out if `make run` just does all the building it needs and then start the server. It looks like you need to do the three steps 
```
$ make shell-ghc
[nix-shell:Carnap]$ make build-ghc
[nix-shell:Carnap]$ make run
```
in sequence.

**Comment by lf-** [comment]
> What I was doing was trying out if `make run` just does all the building it needs and then start the server. It looks like you need to do the three steps
> 
> ```
> $ make shell-ghc
> [nix-shell:Carnap]$ make build-ghc
> [nix-shell:Carnap]$ make run
> ```
> 
> in sequence.

I think you have to do the client build first, with `nix-build -A client -o client-out`. I'm surprised that the order here made it work differently.

**Comment by gleachkr** [comment]
I think this is resovled, but if not, please reopen.
