### ISSUE TITLE
Option to generate table of contents for srv (and others?)

### ISSUE THREAD

**Issue by lf-** [Carnap/Carnap#268]
As part of writing docs, I want to potentially have a big page of reference material, but in order to do that practically, we really need hyperlinks to each section in a table of contents. Pandoc can do this but I'm not sure what needs poking to do it when using it as a library. It must be possible though.

It would be nice if we could have it as a sidebar if it fits on large desktop browsers, and if not, it would appear inline using a media query.

**Comment by gleachkr** [comment]
There's a `writerTableOfContents` option for the `WriterOptions`: 

https://hackage.haskell.org/package/pandoc-2.14.0.2/docs/Text-Pandoc-Options.html

I think, if that's on, `toc` becomes available as a template variable:

https://pandoc.org/MANUAL.html#variables-for-html

So you can interpolate a table of contents into an html template, with a separate variable for the pandoc body.

Maybe for the `srv/` paths (or heck, maybe even assignments), we should include a YAML field that lets you point to a template file?

**Comment by lf-** [comment]
> There's a `writerTableOfContents` option for the `WriterOptions`:
> 
> https://hackage.haskell.org/package/pandoc-2.14.0.2/docs/Text-Pandoc-Options.html
> 
> I think, if that's on, `toc` becomes available as a template variable:
> 
> https://pandoc.org/MANUAL.html#variables-for-html
> 
> So you can interpolate a table of contents into an html template, with a separate variable for the pandoc body.
> 
> Maybe for the `srv/` paths (or heck, maybe even assignments), we should include a YAML field that lets you point to a template file?

I'm thinking if we get the css right so it doesn't degrade the experience for anyone relative to the current state, we could enable it unconditionally, at least for docs.

**Comment by gleachkr** [comment]
It'd probably be a nice thing to have for people writing books, as well. I can probably take a swing at it soon.

**Comment by gleachkr** [comment]
OK, I've added support for using template files. The template filename should have the extension `.template`, and be in the same directory as the pandoc file that it's a template for. You should also be able to use pandoc's "partials" for subtemplates. 

You specify which template to use by adding `template: myTemplate.template` to the YAML header. YAML variables can be interpolated into the template (it'd be a little more elegant if the interpolated variables all came from a single field in the header  YAML, rather than having the entire header interpolable, but I haven't quite figured that out). The variable `toc` can be used to generate a table of contents.

**Comment by gleachkr** [comment]
> it'd be a little more elegant if the interpolated variables all came from a single field in the header YAML, rather than having the entire header interpolable, but I haven't quite figured that out

Looks like this isn't possible short of overriding the HTML writer in pandoc:

https://github.com/jgm/pandoc/blob/235cdea629de95f5a6c40a043e8dff6b19a46d3d/src/Text/Pandoc/Writers/HTML.hs#L243

So I think it's good enough as is. Will close this issue once template usage is documented.

**Comment by gleachkr** [comment]
OK, documented at https://github.com/Carnap/Carnap-Documentation/commit/5c562bb462ca8c0ea6d5d8c135a5c4f90da850ba!
