### ISSUE TITLE
Axioms for OLP systems

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#270]
I put in
```
```{.TreeDeduction .openLogicArithNK options="displayJSON prepopulate" init="now" submission="none" feedback="manual" axiom-Q1=":|-: Ax x' != 0"}
T1 :|-: 0' != 0
```
(see https://carnap.io/shared/rzach@ucalgary.ca/Axiom%20Test.md) but get an error for
```
{"ident":0,"label":"¬0'=0","rule":"AE","forest":[{"ident":2,"label":"Ax x' != 0","rule":"Ax-Q1","forest":[{"ident":3,"label":"","rule":"","forest":[]}]}]}
```
![Screenshot from 2021-07-03 14-29-24](https://user-images.githubusercontent.com/3122348/124366189-1cbf9280-dc0b-11eb-9eb1-43de412e4fae.png)

**Comment by rzach** [comment]
(I did this first for `.openLogicArithNK` which the documentation doesn't mention (it should right?) but same problem for `.openLogicExArithNK`)

**Comment by gleachkr** [comment]
Shoot, it looks like the axiom names are converted to lower-case when pandoc processes the document. The example works with `Ax-q1` as the justification. I think a sensible fix would be to make the axiom names case-insensitive, does that seem OK to you?

Also: at the moment ordinary `.openLogicArithNK` doesn't take axioms, but there's no problem with adding them that I can see.

**Comment by rzach** [comment]
OK for me!

**Comment by gleachkr** [comment]
Great, axiom names are now case insensitive.
