### ISSUE TITLE
"Translation" -> "Solution"

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#272]
Different textbooks might call "translations" "symbolizations" or "formalizations" and my students always worry that their answers are not "standard". Perhaps it's best to be agnostic and change

https://github.com/Carnap/Carnap/blob/99546e377008247c5a1e8de1e294aac8e22584d7/Carnap-GHCJS/src/Carnap/GHCJS/Action/Translate.hs#L121

to say "Equivalent to a correct solution"

**Comment by gleachkr** [comment]
Good idea. How about "equivalent to the given solution"? I worry that "equivalent to P" might have a "not P" implicature, which could be confusing when P is "a correct solution"

**Comment by rzach** [comment]
The student might be ignorant of the way it works and get confused as to who has given what solution.
Maybe just say "Correct!"?

**Comment by gleachkr** [comment]
Right, sounds good (I was a little uneasy with "given"). I'll switch it to "Correct!".
