### ISSUE TITLE
unorganized "add co-instructor" list on instructor page

### ISSUE THREAD

**Issue by maxaeon** [Carnap/Carnap#277]
On the 'Instructor Page,' it would be nice if the list of possible co-instructors to choose from could be alphabetized in order to make finding certain people easier.

(Awesome program so far, can't wait to use it in my intro to logic class.)

**Comment by maxaeon** [comment]
It appears this has been resolved on the website-- thanks!

**Comment by gleachkr** [comment]
Yep, in response to this issue. Thanks for the report!
