### ISSUE TITLE
Proof checker gets into "waiting for parsing to be completed" state on all inferences

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#28]
I'm not exactly sure how or when this happens, or whether it's a bug, but I've gotten myself into a situation where the checker just says "Waiting for parsing to be completed" and I can't tell where the problem is.
For instance:
- At https://gleachkr.github.io/ProofJS/
- click on any top node (above a line marked as an assumption).
- put in a formula
Now all inferences are greyed out and the mouseovers show "waiting for parsing to be completed". But it should show that topmost inference as an error: it has a nonempty premise, but no inference rule is given. If you change the rule label to something correct, it still is waiting for the parser.

![waiting](https://user-images.githubusercontent.com/3122348/67307899-75daa780-f4b6-11e9-9602-5a6193b82882.png)

I'm guessing that what's happening is that the proof parser requires all assumptions to "follow from" an empty node and have a label (n). But if the empty node is missing, or the label is missing, there's nothing in the tree to paint red. You'd have to mouse over the empty space where the label (n) would go to see the error.

Suggestion: a topmost non-empty node gets painted red and you display a hint (eg, "assumptions must be labelled and follow from an empty node" or something)

**Comment by gleachkr** [comment]
Yep, guess is correct. Alternative way of handling this case - maybe it would make sense to treat "P" here as an (unlabelled) assumption?

**Comment by rzach** [comment]
I think that would work. You give a discharge label to an assumption by putting an empty node above it and put the number in the rule label.

**Comment by gleachkr** [comment]
OK, should be fixed by 165df9fe544aa86df92ea53d0b3a231b4148d402
