### ISSUE TITLE
More informative logic prompt

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#288]
Carnap gives you the login prompt whenever you go to a page that requires being logged in (student/instructor home, or `carnap.io/assignments/*`. Now that more and more students get logged in via LTI the login prompt is a bit confusing. Maybe change that page to something like:

>  The page you requested requires that you log in to Carnap first.
>  - If you are a student who logs in via your course website, use the Carnap login link  
>      provided by your instructor on your Learning Management System.
>  - If your instructor has asked you to log in using google, use the link below.
>  LINK: Log in via Google

**Comment by gleachkr** [comment]
Great idea. Done, will be active with next deploy.
