### ISSUE TITLE
Stack Build Errors

### ISSUE THREAD

**Issue by ismailserin** [Carnap/Carnap#289]
When I try to build with stack the following errors occur:
<pre>Building library for Carnap-Server-0.0.0..
[36 of 50] Compiling Util.Handler

/home/iserin/Carnap/Carnap-Server/<b>Util/Handler.hs:61:25: </b><font color="#DC322F"><b>error:</b></font>
    Variable not in scope: ghcjs_allactions_lib_js :: Route Static
<font color="#268BD2"><b>   |</b></font>
<font color="#268BD2"><b>61 |</b></font>     addScript $ StaticR <font color="#DC322F"><b>ghcjs_allactions_lib_js</b></font>
<font color="#268BD2"><b>   |</b></font><font color="#DC322F"><b>                         ^^^^^^^^^^^^^^^^^^^^^^^</b></font>

/home/iserin/Carnap/Carnap-Server/<b>Util/Handler.hs:62:25: </b><font color="#DC322F"><b>error:</b></font>
    Variable not in scope: ghcjs_allactions_out_js :: Route Static
<font color="#268BD2"><b>   |</b></font>
<font color="#268BD2"><b>62 |</b></font>     addScript $ StaticR <font color="#DC322F"><b>ghcjs_allactions_out_js</b></font>
<font color="#268BD2"><b>   |</b></font><font color="#DC322F"><b>                         ^^^^^^^^^^^^^^^^^^^^^^^</b></font>

/home/iserin/Carnap/Carnap-Server/<b>Util/Handler.hs:70:29: </b><font color="#DC322F"><b>error:</b></font>
    Variable not in scope: truth_tree_lib_css :: Route Static
<font color="#268BD2"><b>   |</b></font>
<font color="#268BD2"><b>70 |</b></font>     addStylesheet $ StaticR <font color="#DC322F"><b>truth_tree_lib_css</b></font>
<font color="#268BD2"><b>   |</b></font><font color="#DC322F"><b>                             ^^^^^^^^^^^^^^^^^^</b></font>

/home/iserin/Carnap/Carnap-Server/<b>Util/Handler.hs:72:25: </b><font color="#DC322F"><b>error:</b></font>
    Variable not in scope: ghcjs_allactions_runmain_js :: Route Static
<font color="#268BD2"><b>   |</b></font>
<font color="#268BD2"><b>72 |</b></font>     addScript $ StaticR <font color="#DC322F"><b>ghcjs_allactions_runmain_js</b></font>
<font color="#268BD2"><b>   |</b></font><font color="#DC322F"><b>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>

/home/iserin/Carnap/Carnap-Server/<b>Util/Handler.hs:73:23: </b><font color="#DC322F"><b>error:</b></font>
    Variable not in scope: truth_tree_lib_js :: Route Static
<font color="#268BD2"><b>   |</b></font>
<font color="#268BD2"><b>73 |</b></font>     addInlineScript $(<font color="#DC322F"><b>juliusFile =&lt;&lt; pathRelativeToCabalPackage &quot;templates/createTrees.julius&quot;</b></font>)
<font color="#268BD2"><b>   |</b></font><font color="#DC322F"><b>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</b></font>

--  While building package Carnap-Server-0.0.0 (scroll up to its section to see the error) using:
      /home/iserin/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:Carnap-Server exe:Carnap-Server --ghc-options &quot; -fdiagnostics-color=always&quot;
    Process exited with code: ExitFailure 1</pre>
Since I am not a programmer by profession, I am unable to interpret these errors. How can I overcome these errors? Thanks in advance.

**Comment by lf-** [comment]
Hi! These errors are caused by there not being a built client at client-out, as well as there not being a built truth tree plugin at truth-tree-out in the root of the repository (there may also be funny cache issues going on once you fix it if I recall correctly).

I recommend using Nix instead of Stack, as you will need Nix anyway to build or acquire both of these components, and the makefile will handle them both for you when you use `make run` or `make build-ghc` after setting up Nix with the instructions in the readme. 

If you need some more help, Graham and I are on the Matrix/IRC channel linked in the readme :)

**Comment by ismailserin** [comment]
Hi If-,
I followed your recommendation and experienced another kind of difficulty. Nix consumes a lot of memory. My PC has 8GB memory and it seems insufficient. By the way, are all these procedures suitable for the production environment too?

**Comment by lf-** [comment]
I've replied re: the Nix memory issue on Matrix.

> By the way, are all these procedures suitable for the productions environment too

Yes, the production version of the software is built either with Nix (`nix-build -A server`, which you can then deploy with NixOps or other methods; this is what my team does at UBC) or Stack (`stack build` assuming the client side components are all there. This is what Graham currently uses). The build process documentation is a work in progress.

We also use Nix to build Docker images which are published on GitHub container registry. See the .github/workflows/ci.yaml for how that's done. There's documentation at https://carnap.io/srv/doc/administration.md for all of this.

**Comment by ismailserin** [comment]
Thank you for your reply. For my part, I have to read these documents in detail.
