### ISSUE TITLE
System not being recognized for model checking questions

### ISSUE THREAD

**Issue by philip-davis** [Carnap/Carnap#295]
I am having an issue changing systems for model checking questions. If I am understanding correctly, some systems allow me to use predicates A, B, etc. For example:

```
~~~{.CounterModeler .Simple  system="thomasBolducAndZachFOL"}
3.1 Ax->Bx
~~~
```

But when I do this, I get an error like:

```
(line 1, column 7): unexpected unbound variable expecting a constant, white space, operator, "->", ">", "\8594", "\8835", "only if", "=>", "<->", "<>", "\8596", "\8801", "if and only if" or "<=>"
```

In fact, the [documentation on model checking problems](https://carnap.io/srv/doc/modelchecker.md) seems to be showing the same error. Has the way to change systems for these problems changed?

**Comment by gleachkr** [comment]
Thanks for catching that documentation issue! 

You're correct that some systems (including `thomasBolducAndZach`) let you use the full uppercase alphabet for predicate symbols. I think what's going wrong in the example that you're giving (and also in the documentation) is that the particular languages in question also don't want to count open formulas (formulas with unbound free variables) as well formed. The parsers for these languages were previously a little more permissive, but they've now been tightened up so as not to accept open formulas. If you change your example to read something like:

    ~~~{.CounterModeler .Simple  system="thomasBolducAndZachFOL"}
    3.1 Ax(Ax->Bx)
    ~~~

then it ought to generate the model checking problem you're after.
