### ISSUE TITLE
Multiple assignments to same column in database when updating assignment data in self-hosted Carnap instance

### ISSUE THREAD

**Issue by diegofernandess** [Carnap/Carnap#296]
When one tries to update assignment data, at any field, Carnap server (built from the latest source) gives the following error message:

> Carnap-Server[58514]: 05/Jan/2022:23:02:23 -0300 [Error#yesod-core] SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "multiple assignments to same column \"availability\"", sqlErrorDetail = "", sqlErrorHint = ""} @(Carnap-Server-0.0.0-EK3YQrWAymL5VtErXmccMr:Foundation Foundation.hs:281:9)

The SQL command submitted when trying to change the "description" field from "" to "bla" is:

> STATEMENT:  UPDATE "assignment_metadata" SET "duedate"='2022-02-26 02:59:00Z',"visible_from"=null,"visible_till"=null,"grade_release"=null,"point_value"=null,"total_problems"=null,"availability"=null,"availability"=null,"description"='bla' WHERE "id"=33 

Does any one have the same issue?

**Comment by gleachkr** [comment]
I don't think I've seen this one before. I'll look into it. Could you send some more details on how to reproduce? In particular:

1. What database backend are you using?
2. What are the exact steps you took to trigger the error?

**Comment by diegofernandess** [comment]
Curious. As far as I noticed, every other functionality related to the database access is working normally. I'm using Postgresql ver. 14, and the steps to reproduce are the following:

- Create some course, e.g. "Logic-Test";
- Upload an assignment file, e.g. example.md:
```
Test example 
 ~~~{.TruthTable .Simple}
 1. (P /\ Q)
 ~~~
```
- Assign  example.md to Logic-Test, setting no other parameters;
- Now under the tab "Assign Uploaded Documents", in the field "Edit Assignments", click on the gear. Under the pop-up window "Update Assignment Data", write "bla" in the field "Description" and click on "update" (actually, only clicking on "update" with no modifications already triggers the error).

**Comment by gleachkr** [comment]
Thank you for the bug report! I think I've found the source of the trouble. The fix was just pushed. If it works for you, we can close the issue.

**Comment by diegofernandess** [comment]
Now it works, thank you very much!
