### ISSUE TITLE
Allow constraints on translation exercises

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#30]
It would be nice to have a way to use the translation checker for exercises that require students to provide solutions of a specific form. For instance, there could be an option to require the solution to be in conjunctive normal form, or only use connectives from a specified set. Eg then you could do something like:
```
~~~{.Translate .Prop option="onlyCNF"}
II.3 A -> ~B: Put the sentence into CNF
~~~
```
Options could be:
- [x] Conjunctive normal form
- [x] Disjuncive normal form
- [x] Prenex normal form
- [x] Only uses connectives from a specific set (`only-connectives="\/ ~"`)
- [x] Only uses a certain number of connectives

**Comment by rzach** [comment]
(`only-connectives` might come in useful for doing the others: e.g., a sentence is in CNF if it only uses connectives from &, \/, ~, and anything in the scope of an & is such that [it only uses \/ and ~ and anything in the scope of an \/ only uses ~] and also anything in the scope of an ~ is atomic.

**Comment by gleachkr** [comment]
Ok, this is partly ready. The syntax is `tests="$FOO"` where $FOO is a space-separated list of tests.

Currently the tests are `CNF` and `DNF`. Both are available for propositional and first-order languages. If all goes well, will deploy this afternoon.

**Comment by gleachkr** [comment]
Just deployed.

**Comment by gleachkr** [comment]
Added a few new tests. We've got: `maxCon:`, `maxAnd:`, `maxOr:`, `maxNeg:`,`maxIf:`, `maxIff:` and `maxAtom:` for setting a maximum allowable number of occurences of connectives, conjuntions, disjunctions, conditionals, biconditionals, and atomic sentences respectively. By combining these, you can also restrict to a subset of connectives (e.g. by setting the maximum number of conjunctions and disjunctions both to zero).

The test name should be followed by a number (with no space in between) like `maxCon:3`. So you could have something like `tests="CNF maxOr:5"`, for example. Just deployed, so should now be live.

**Comment by gleachkr** [comment]
The prenex normal form test is now available, as `PNF`.

**Comment by rzach** [comment]
Cool! Thanks! Parhaps also maxFalse for # of occurrences of _|_?

**Comment by gleachkr** [comment]
Good idea. Will do!

**Comment by gleachkr** [comment]
Added with 94bf449.

**Comment by gleachkr** [comment]
Let's call this done, and put any other ideas for constraints in new issues as they occur.

**Comment by rzach** [comment]
Thanks so much!
