### ISSUE TITLE
Can't unassign textbook problem set

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#304]
I have a problem set from the book assigned to a course, but clicking on the trashcan icon doesn't delete it.
(Assigning and removing uploaded documents works)

**Comment by gleachkr** [comment]
I did a quick test, and I can't seem to reproduce this - I seem to be able to delete assignments from the textbook, as admin and when I'm signed in as a regular instructor. Any ideas on how I might be able to reproduce the problem? (This is the trashcan icon under the "Assign Textbook Problems" tab on the instructor page?)

**Comment by rzach** [comment]
Yes, the "manage problem sets" in the "assign textbook problems" tab.  I made you a co-instructor on the course in questions.
PS I tried it on both Firefox and Chrome so I don't think it's a browser issue. I have a suspicion: Inspecting the action shows that the name of the course is `'Calgary Phil 279 L01 Spring 2022\t'` with a trailing tab character maybe that's the problem?

**Comment by gleachkr** [comment]
Thanks! yep, it's the tab character. I've changed this API to use the course id rather than the course title, which should avoid any future trouble with special characters. Deploying now.

**Comment by gleachkr** [comment]
Took the liberty of deleting that stray problem set from your course. Issue seems to be resolved!

**Comment by rzach** [comment]
Excellent, thanks!
