### ISSUE TITLE
How to get TA status on Carnap?

### ISSUE THREAD

**Issue by ParsaEsmkhani** [Carnap/Carnap#306]
Hi so I’m cooperating on a Carnap project with my prof and I’d like to get TA status so I can edit things, not sure how to do so.

**Comment by maxaeon** [comment]
Just reach out to the person in the contact info on the Carnap page (it was Graham, I believe, last I knew-- gleachkr@ksu.edu). Best of luck with your class (or whatever project it is you're working on)! :)
