### ISSUE TITLE
Syntax problem concerning the translation

### ISSUE THREAD

**Issue by ismailserin** [Carnap/Carnap#307]
While translating "messages\en.msg" into Turkish, I ran into a problem. Since the syntax of Turkish is different from English, the translations of the sentences that are separated into different lines cause problems. For example, HomepageText1-9. In order to get meaningful Turkish UI, it would be better to put the complete sentence in each line.

_Originally posted by @ismailserin in https://github.com/Carnap/Carnap/issues/271#issuecomment-1120203987_

**Comment by gleachkr** [comment]
Oh, right. I should have thought of that!

One sentence per-line would be ideal, but occasionally there are lines that include links, and there needs to be some indication of which words should be part of the link. One idea is to break sentences that contain links into "prefixes", "links" and "suffixes", while using numbers to indicate that they're all part of the same sentence. Then the translator can have some freedom to restructure the sentence (the meaning of the translated prefix doesn't have to be the same as the meaning of the untranslated prefix, as long as the sentence keeps its meaning), and to indicate which words belong in the link.

It might look something like this: 

```
HomepageWelcome: Welcome to Carnap.io
HomepageSubtitle: A formal logic framework for Haskell
HomepageHeader: Background
HomepageTextPrefix1: Carnap is a free and open software framework written in
HomepageTextSuffix1: for teaching and studying formal logic. 
HomepageTextPrefix2: Carnap powers logic courses at
HomepageTextLink2: dozens of colleges and universities
HomepageTextSuffix2: around the world.
HomepageText3: If you're a student in a course that uses Carnap, please follow the links at the top of the page to log in and to access course materials.
HomepageTextPrefix4: If you're just curious about Carnap, you can find some general information on our
HomepageTextLink4: about
HomepageTextSuffix4: page. 
HomepageTextPrefix5: If you're interested in the project, and would like to use Carnap in a class you're teaching, or get involved in some other way, please feel free to 
HomepageTextLink5: get in touch!
```

Would that be workable?

**Comment by ismailserin** [comment]
It largely solves the problem, but what do we do when there is no link text like in cases HomepageTextPrefix1 and HomepageTextPrefix2?  In addition to this, the reference of the quotation from Carnap is not in the tr.msg file.

**Comment by gleachkr** [comment]
> It largely solves the problem, but what do we do when there is no link text like in cases HomepageTextPrefix1 and HomepageTextPrefix2? 

Hm - I left that out because the link text was a proper name that might not make sense to translate. But maybe it'd be better to leave it in for uniformity. Then this would look like:

```
HomepageWelcome: Welcome to Carnap.io
HomepageSubtitle: A formal logic framework for Haskell
HomepageHeader: Background
HomepageTextPrefix1: Carnap is a free and open software framework written in
HomepageTextLink1: Haskell
HomepageTextSuffix1: for teaching and studying formal logic. 
HomepageTextPrefix2: Carnap powers logic courses at
HomepageTextLink2: dozens of colleges and universities
HomepageTextSuffix2: around the world.
HomepageText3: If you're a student in a course that uses Carnap, please follow the links at the top of the page to log in and to access course materials.
HomepageTextPrefix4: If you're just curious about Carnap, you can find some general information on our
HomepageTextLink4: about
HomepageTextSuffix4: page. 
HomepageTextPrefix5: If you're interested in the project, and would like to use Carnap in a class you're teaching, or get involved in some other way, please feel free to 
HomepageTextLink5: get in touch!
```

Does that seem better?

> In addition to this, the reference of the quotation from Carnap is not in the tr.msg file.

Ah right. Similar thinking on my part. It'd probably make more sense to include that. I'll add it in when I redo the `msg` files after we decide what to do about the current issue.

**Comment by ismailserin** [comment]
> Does that seem better?

Yes. 
Now we can translate properly. Thanks!

**Comment by gleachkr** [comment]
I've redone the msg files for the home page and the info page. These should hopefully work better. I'm sure other things will come up, so please feel free to open more issues as problems arise.
