### ISSUE TITLE
 Issue with Carnap on Chrome in Android Devices

### ISSUE THREAD

**Issue by diegofernandess** [Carnap/Carnap#308]
I'm not sure whether this is an issue related with Carnap, or with the Chrome browser in Android, but when accessing assignments [such as these](https://carnap.io/shared/sswartzer@gmail.com/Practice%20Exercises-06-26.md) in such settings, the "enter" button at the keyboard is interpreted as "next", so it is not possible to submit an answer for any item. I tested this in a couple of Android devices and observed the same behavior. At Firefox, the problem does not happen.

**Comment by gleachkr** [comment]
Thanks for catching this!

I think what's going on is this. The software keyboard on android (maybe other software keyboards too) decides what it's going to use the lower right key for contextually. When there's just one input, in the android I've got access to, it shows an icon that looks like `-->`, and sends an `Enter` keyup event. When there's more than one input, it looks like `-->|`, and doesn't send any keyup/down events, but instead navigates to the next input.

Luckily, it looks like [you can add a hint for the intended behavior](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint).

I've gone ahead and done that for the translate and syntax-check exercise types, so they should now work properly. Android chrome is pretty aggressive about caching, so you may need to [clear it manually](
https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DAndroid).

**Comment by diegofernandess** [comment]
Many of my students access Carnap via Google Chrome on Android devices, they reported the issue to me. 

Now it is working, thank you very much!
