### ISSUE TITLE
Allow givens for countermodel checker

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#31]
It's sometimes useful for model checking exercises to fix part of the interpretation. Perhaps the model checker could accept "givens" the way the truth table checker does. E.g., "make this sentence true in a domain consisting of 0, 1, 2"; or "Make the sentence true in the given interpretation by only changing the referent of `a`."

**Comment by rzach** [comment]
Since I'm doing semantics again, I'm reminded of this. I think it would increase the usefulness of the countermodel checker a lot.  To be clear, I'm hoping mainly for immutable givens, e.g., if I say

    ```{.CounterModeler .Simple options="strictGivens"}
    1.1 AxF(x), ExG(x)
    |Domain:0,1
    |F(_): 0
    ```
Then domain and interpretation of F would be fixed and Carnap would only allow input for `G(_)`.

**Comment by gleachkr** [comment]
Ready for testing! Should work as you've specified.

Setting `strictGivens` disables the inputs and adds a little tamper-protection for provided givens. I've also adjusted the parsing for givens, so that they're not quite so allergic to whitespace.

The string to the right of the `:` in the specification of givens should match the desired value of the corresponding input, so for propositions it needs to be either "True" or "False".

**Comment by rzach** [comment]
Amazing, thank you! Playing around with it now. First minor thing: if there are givens, constants are not sorted alphabetically (although if option `strictGivens` is active, they are).

**Comment by gleachkr** [comment]
Thanks! I'll take a look tomorrow.

**Comment by rzach** [comment]
I think it doesn't like givens for multi-place predicates and for functions; they're just ignored.

**Comment by gleachkr** [comment]
Hm. Could you send the pandoc?

**Comment by rzach** [comment]
First one should have givens for A and f:
https://carnap.io/shared/rzach@ucalgary.ca/379%20Worksheet%20Semantics%20and%20Theories.md

    ~~~{.CounterModeler .Simple system="thomasBolducAndZachFOL2019" submission=none}
    W6.1 Ax(A(f(x), b) -> Ey A(y,f(x)))
    |Domain: 0, 1, 2
    |A:[0,0]
    |f:[0;0]
    |b: 1
    ~~~

**Comment by rzach** [comment]
Ah wait I see what I did wrong

**Comment by rzach** [comment]
Yeah nevermind sorry

**Comment by gleachkr** [comment]
No worries! I think it's fair to describe the documentation right now as "incomplete".

**Comment by gleachkr** [comment]
OK, the different inputs should now always be sorted alphabetically!

**Comment by gleachkr** [comment]
Just pushed some documentation. Good to close?

**Comment by rzach** [comment]
Thanks again!
