### ISSUE TITLE
[Question] Does not render submitted answers after page reload

### ISSUE THREAD

**Issue by ayushmanchhabra** [Carnap/Carnap#313]
Is this a bug or by design or maybe a limitation of pandoc?

**Comment by gleachkr** [comment]
This is by design (to nudge everyone away from copy-paste).

However, instructors can add this type of functionality by using a JavaScript extension. Something along those lines is `save-work.js`, here: https://github.com/dsanson/carnap-javascript

**Comment by ayushmanchhabra** [comment]
> This is by design (to nudge everyone away from copy-paste).

AH of course 😆

> https://github.com/dsanson/carnap-javascript

This is super neat.
