### ISSUE TITLE
Nix-shell issue

### ISSUE THREAD

**Issue by njrardin** [Carnap/Carnap#315]
I'm trying to get started contributing to this project but as I follow along with the instructions in the readme I'm getting the following series of warnings and errors after attempting to run the `nix-shell` command:

```
yarn run v1.22.11
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ parcel build src/lib.ts --global Rudolf --public-url .
⠋ Building.../bin/sh: lscpu: not found
⠙ Building lib.ts...⠹ Building lib.ts...Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
⠸ Building lib.ts...⠼ Building react.production.min.js...⠴ Building react.production.min.js...⠦ Building react.production.min.js...⠧ Building react.production.min.js...⠇ Building carnapAdapter.ts...⠏ Building carnapAdapter.ts...⠋ Building scheduler.production.min.js...⠙ Building scheduler.production.min.js...⠹ Building scheduler.production.min.js...⠸ Building scheduler.production.min.js...⠼ Building scheduler.production.min.js...⠴ Building scheduler.production.min.js...⠦ Building scheduler.production.min.js...⠧ Building scheduler.production.min.js...⠇ Building ZoomOutTwoTone.js...⠏ Building ZoomOutTwoTone.js...⠋ Building ZoomOutTwoTone.js...⠙ Building ZoomOutTwoTone.js...🚨  /build/n7zgb51fma3106kldzq4ixrwwl3lb7rc-truth-tree-src/node_modules/@material-ui/icons/esm/RouterSharp.js: EMFILE: too many open files, open '/build/n7zgb51fma3106kldzq4ixrwwl3lb7rc-truth-tree-src/node_modules/@material-ui/icons/esm/RouterSharp.js'
Error: EMFILE: too many open files, open '/build/n7zgb51fma3106kldzq4ixrwwl3lb7rc-truth-tree-src/node_modules/@material-ui/icons/esm/RouterSharp.js'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error: builder for '/nix/store/6qkcnpfahy0cnv4dqmk23rpb1z98z8ar-truth-tree-0.1.10.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/mk9ajd4kdi0i1la92y21qj8p5qx926db-hoogle-local-0.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/grrpcqkkif05zl54iy0q09avv82bf9dv-ghc-8.10.6-with-packages.drv' failed to build
```

For additional context, so far all I've done is clean install Nix, clone the repository, and then attempt to follow the commands as listed in the readme (including cachix). I am running this within a WSL2 instance as well just in case that is related.

(side note: If this isn't a Carnap related error my apologies. I'm still fairly new to some of this stuff)

**Comment by njrardin** [comment]
I did a clean re-install of my WSL2 Ubuntu distribution and this error stopped occurring. Unfortunately I don't know how to reproduce or fix this error any other way (in case someone comes across this with a similar error).

**Comment by njrardin** [comment]
I did a clean re-install of my WSL2 Ubuntu distribution and this error stopped occurring. Unfortunately I don't know how to reproduce or fix this error any other way (in case someone comes across this with a similar error).

**Comment by gleachkr** [comment]
@njrardin - thanks for the follow up. I think this is an issue with file-descriptor limits that systems sometimes place on virtualized linuxes, and with the number of files that yarn needs open in order to build the truth-tree component that's bundled with the server. I've seen something similar in the context of some containerized builds, and it makes sense that it might show up in WSL. It's good to know that this can happen with WSL. I'll keep a eye out for it in the future.

**Comment by njrardin** [comment]
For some reason, after I got it to work once after clean re-installing Ubuntu in WSL2, it is occurring again. I suppose I'm back to investigating solutions for it.

**Comment by njrardin** [comment]
I have discovered a workaround that fixed this issue.

The issue that's occurring is that WSL2 (at least in Ubuntu 24.04.1 in WSL kernel version 5.10.102.1) has a default hard open file limit of 4096 for all users which, for some reason, does not update on reboot even if reset by superuser.

However, if you first use command
`sudo su` 
to go into superuser, and then edit
`/etc/sysctl.conf` and  `/etc/security/limits.conf` 
to increase ulimit for the system and/or specific users
(as described in [this article](https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/)), you can operate under the updated file open limits by using command
`su yourUserName`
which just returns to your normal user profile but with regard to the edited conf files.

Essentially, on reboot, WSL ignores the changed conf files, but when you `su` into the same user as default it considers them. (more info on this weirdness can be found [in this issue page on WSL](https://github.com/microsoft/WSL/issues/1576))

Side note: this only has to be done whenever the full build process has to run (which wants to open a ton of file descriptors). This doesn't have to be done each time nix-shell is used.
