### ISSUE TITLE
Assignment went missing

### ISSUE THREAD

**Issue by dmgray2** [Carnap/Carnap#338]
I had an assignment that was up for the past 3 weeks.  I do not believe I entered a date for it to be removed although it had a due date.  I went on today and the assignment isn't anywhere except the 'Manage Uploaded Documents' area.  I downloaded the grades and the grades for that assignment are missing.  Any ideas on how to retrieve the grades for this assignment? I was thinking about reuploading the assignment to the class, but I was worried that would reset the gradebook.
Thanks,
DMG

**Comment by dmgray2** [comment]
@gleachkr @JakeEhrlich see above.
Thank you,
@DMG-17

**Comment by gleachkr** [comment]
Resolved over email
