### ISSUE TITLE
ZachFOL2019Plus uses wrong system

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#34]
I think something is wrong with proof checker system ZachFOL2019Plus. 

If I put in `A :PR` it should accept that as a premise but the warning triangle hint says it expect a "SHOW" which the forallx systems don't use.

See bottom of page at https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20VII.md

**Comment by gleachkr** [comment]
OK, I'm seeing this behavior in the final playground. I think the issue is that the string giving the system should be `.ZachFOLPlus2019` rather than `.ZachFOL2019Plus`. Does that fix it?

**Comment by rzach** [comment]
Ah, right. Yes it does. Sorry, nevermind.

**Comment by gleachkr** [comment]
No worries!
