### ISSUE TITLE
Allow multiple solutions in translation exercises

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#35]
It's sometimes useful or even necessary to allow multiple sentences as equally good translations.
- If the sentence to be symbolized is ambiguous
- If you want to allow different symbolizations which either take something as implied or implicated (e.g., "Only Pavel is happy" -- does it imply or just implicate that Pavel is happy?)
- In mixed domains a predicate my imply a restriction to one kind, but we want to allow making the restriction explicit. E.g., if P(x) is "is a person" and C(x) "is a cook" then we might want to accept both `Ax((P(x) /\ C(x)) ->` and `Ax(C(x) ->` as symbolizations of "All cooks..."
- The equivalence test doesn't catch even logically equivalent symbolizations when identity is present. If I could put in more than one acceptable translation that limitation could be overcome without implementing a full-fledged identity prover. (Eg: "Only Pavel is happy" can be symbolized by both `H(p) & Ax(H(x) -> x = p)` and `Ax(H(x) <-> x=p)` but the checker doesn't recognize that these are equivalent.

**Comment by rzach** [comment]
Test case for last issue: V.21 in https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20V.md

It accepts `H(g) & Ax(H(x) -> x=g)` but not `Ax(H(x) <-> x=g)`

V.26 accepts 
`ExEy((H(x) & H(y)) & (~x=y & Az(H(z) -> (z=x \/ z=y))))` but not 
`ExEy((H(x) & H(y)) & ~x=y) & ~ExEyEz(((H(x) & H(y)) & H(z)) & (~x=y & (~x=z & ~y=z)))`

**Comment by rzach** [comment]
Is this deployed yet? What's the syntax for multiple solutions? Just comma separated?

**Comment by gleachkr** [comment]
Nope, sorry, not quite yet - accidentally closed this instead of #37.

**Comment by gleachkr** [comment]
OK, just deployed. The syntax is now that the problem should consist of a comma separated list of translation targets, followed by a colon, followed by a sentence to be translated. I'll leave the issue open for a bit to make sure this works for your case.

**Comment by rzach** [comment]
Works like a charm! Thanks so much.
