### ISSUE TITLE
Proof checker complains about correct proof

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#36]
It seems to me that this proof should be accepted.
<img width="653" alt="Proof" src="https://user-images.githubusercontent.com/3122348/68165614-1ef4b980-ff1d-11e9-9bd5-f5884b021ffc.png">
But the playground box at the very end of https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20VII.md
doesn't like it. Here it is to cut-and-paste:
```
    ~∀x(A(x) → ∃y A(y)) :AS
        A(c) :AS
        Ey A(y) :EI 2
    A(c) → ∃y A(y) :->I 2-3    
    ∀x(A(x) → ∃y A(y)) :AI 4
    !? :~E 1,5
∀x(A(x)→∃y A(y)) :IP 1-6
```

**Comment by gleachkr** [comment]
Puzzling. Thanks for the catch. I'll get on this ASAP tomorrow.

**Comment by gleachkr** [comment]
OK, got it, hopefully. It looks like there was an "off by one" error in a function that needs to generate indicies for variables. This had been sitting around for a while, but (I think) started causing trouble once I used it for something in the Gentzen/Prawitz rewrite of natural deduction checking. I'll take care of #37, and deploy the fixes for that issue and this one shortly.

**Comment by gleachkr** [comment]
OK, got it, hopefully. It looks like there was an "off by one" error in a function that needs to generate indicies for variables. This had been sitting around for a while, but (I think) started causing trouble once I used it for something in the Gentzen/Prawitz rewrite of natural deduction checking. I'll take care of #37, and deploy the fixes for that issue and this one shortly.
