### ISSUE TITLE
Model checker gives wrong hint if conclusion is true

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#39]
If you put in an argument and ask for a countermodel to validity, but make the conclusion true, and hit check you'll get a hint that says "Not all conclusions are false in this model. Take another look at: ..." but the formula displayed is the first premise, not the conclusion.

Eg problem 8 on https://carnap.io/shared/rzach@ucalgary.ca/279%20F19%20Problem%20Set%205.md with domain 0,1, R = [0,0],[0,1],[1,0], and a = 0

**Comment by gleachkr** [comment]
Yep, thanks. A silly typo. Deploying the fix.
