### ISSUE TITLE
Language of arithmetic

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#42]
It would be great if Carnap could deal with the language of arithmetic as used in the Open Logic Project; then it could be used (for symbolization and also proofs with the LK or ND proof checkers) for exercises from there. 

- Constant: 0
- Postfix unary function: '
- Infix binary functions: +, * (rendered as \times)
- Infix binary relation: <

**Comment by gleachkr** [comment]
As a warm up, 42f9fa519199459312c7734df07b972b5f23eb7a gets (axiom-free, only logical inferences) set theory working for OLP NK (a little easier than arithmetic since we've already got the syntax). The system string is `.openLogicSTNK`, and the easiest abbreviation for ∈ is `in`, so a typical invocation might be:

    ```{.TreeDeduction .openLogicSTNK init="now" }
    1.1 :|-: ~∃yAz(z in y <-> z in z)
    ```

I'm still being a little cautious about pushing updates, since it's conceivable that there are still finals going on, but I'll deploy this weekend.

**Comment by gleachkr** [comment]
OK, 8636e1dbc02a03d10882a2ebf10282c3ad3c2c7f gets (axiom-free) arithmetic working for OLP NK. The system string is `.openLogicArithNK`, so a typical invocation might be:

    ```{.TreeDeduction .openLogicArithNK init="now" }
    1.1 :|-: a + b = b + a -> a + (a + b) = a + (b + a)
    ```   

This is now deployed and ready for testing (though, of course, no rush! Holidays!)

**Comment by rzach** [comment]
Ok, finally got around to trying this out.

a. ND trees look like they work ok. But I seem to recall that the checker should prefill the endformula.  Did that change or is that a bug? (It doesn't do it in the old systems either).
b. Does this/should this work with other types of exercises too (`.Translate`, `.CounterModeler`)?  It doesn't seem like it does although maybe I just don't know the right system strings. Neither `.openLogicArithNK` nor `system="elementaryArithmetic"` worked.
c. I think it would be useful (and I don't think it could ever hurt) to allow arbitrary function and predicate symbols in both languages in addition to the basic vocab. (I saw in the code somewhere that elementarySetTheory allows `P` and `Pow` for power set but that seems to be turned off for OLP.  That would conflict but I think `p` as a unary function for the power set would work just as well.

**Comment by gleachkr** [comment]
Thanks!

1. I think that you need to set `options="prepopulate"` to prefill the end formulas in tree systems, is that not working?
2. Doesn't work with other types of exercises yet. `Translate` would be pretty straightforward, modulo a decision about what equivalence should mean. The FOL equivalence test will work for these languages though. You could also add some basic algebra 101 rewrites for arithmetic, to get a more inclusive notion of equivalence. Countermodeler is harder, since it's then necessary to specify what the semantics of these language should be in finite first-order models, but it'd be possible. 
3. Entirely agree - I actually had a little bit of a plan here. Basically, I was thinking that in addition to the "strict" variants of each language, there should be "extended" variants, that don't just allow arbitrary (numerically-indexed) predicates but allow predicates and function symbols indexed by strings, which display as just the string. I was thinking that that, embedded in a system that allows the instructor to specify axioms at runtime, and allows the student to create derived rules, could make for an interesting series of units in some future textbook (though I'm honestly unsure if this is too pedagogically ambitious, or if proving anything worthwhile would be too tedious without really robust tactics).

**Comment by rzach** [comment]
1. Lol I forgot about that I think I even suggested we don't always wont it prepopulated. 
2. I think it would be useful to have translation and countermodeler exercises just for the parser. E.g. it would allow for simple questions such as "Translate 0 is not a successor" that accepts both Ax x'!=0, ~Ex x'=0, Ax 0!=x', and ~Ex 0!=x, which the standard test would.  Or "say that there is an empty set", or even things like "what is the result of substituting 0+0 for all free occurrences of x in "Ay y != x'" etc. The countermodeler would be useful for simple nonstandard models.
3. That would be sweet. But even allowing the simple symbols would be useful for exercises in the language. Eg I use a language in OLP with 0, ' and predicate symbols coding Turing machine configurations, and if the language accepted additional predicate symbols I could assign simple proofs in that language.

**Comment by gleachkr** [comment]
For 3, are predicates of the kind we've already got preferable, or arbitrary string predicates?

**Comment by rzach** [comment]
Hm it's gotta be one or the other, huh?  I guess arbitrary strings is more flexible. (Will the parser allow `Q_a` then? I think I have examples with strings e.g., `Prime(x)` but also non-numerical subscripts eg `S_a(x)`

**Comment by gleachkr** [comment]
Could do two langugages, one with regular predicates and function symbols, and one with strings for predicates and function symbols. I was thinking that strings here ought to mean alphanumeric pluse underscores and first character in [a..zA..Z]. Capital letters would mean predicates, and lower-case would mean function symbols, with parentheses indicating arguments. So ordinary predicates like P(a) and P_1(a) would be sort of subsumed, and both `Prime(x)` and `S_a(x)` would be well-formed atomic formulas.

**Comment by gleachkr** [comment]
Ok, proof trees in the extended language (with string predicates and function symbols) should be good to go! The system string is `.openLogicExtendedArithNK`. Incidentally, these systems don't have inequality parsing. Should that be added?

**Comment by rzach** [comment]
Ok this looks like it works great.  `Qa(0)` works and `Q_a(0)` works too (the latter probably internally is `Q__a` but we don't care.)

One problem I see is that `<` is rendered as ⊆.

Don't hate me but I wonder if there is any downside to having just one language for all the OLP systems, which allow string predicates and function symbols (since Carnap is ok with `_` being part of the string, this includes the standard one-letter-underscore-subscript format), and all the relations and functions from both the arithmetic and set theory vocabulary. The only problem I see is that `<` is rendered as  ⊆ (which it shouldn't) but then we can't also use `<` for the subset relation (which would be nice to include although it's not officially part of the language). Maybe we can have `<` for <, `<=` for ≤, and `<<` for ⊆? (Fira Logic makes `<=` into a ligature for ⇐ so that might be a problem). Bonus points if we can parse all of them with a `!` for negation just like `!=`.

If it's much easier to have separate set theory and arithmetic languages that's fine too.  But anything I can think of wanting to do I could do in the combined language and there might be future applications where a combined language would be necessary (eg second order arithmetic?).

**Comment by gleachkr** [comment]
Thanks for the catch with ⊆. Should be fixed by an update that's now deploying.

No problem, I think, with a mixed language that adds set theory functions and relations, or with just having all three languages. I wonder, though, if it'd make sense to configure the mixed language lexicon to be a little more complicated than just the union of the two given lexicons? For example, maybe (with an eye on higher-order arithmetic), such a language should be many-sorted, so that we don't need to decide what `{{},5} * 2` is?

Right now, the parsing for set theory symbols is

|symbol        |parsing                         |     
|--------------|--------------------------------|
|subset        | "⊆",  "<(", "<s", "within"     |
|element       | "∈",  "<<", "<e", "in"         |
|complement    | "/"                            |
|powerset      | "P()" "Pow()                   |
|union         | "U", "∪"                       |
|intersection  | "I", "∩"                       | 

But this hasn't gotten a ton of thought, and is certainly open to amendment.

**Comment by rzach** [comment]
I think (for the foreseeable future at least) it will be enough to provide the parser so that proof (and perhaps translation and even model checker) exercises can be run.  I (or whoever assigns them) can decide what language elements we want to allow the students to use.  So eg if I tell them to prove a sentence in the basic set theory language (ie only in) then sure they can use Pow or {5}*3 or whatever else the parser might accept -- but those just won't figure into a correct proof. (E.g., if they don't have the defining axiom of Pow as a premise, they can't use Pow meaningfully in a proof; if I tell them they should symbolize "a is the power set of b" they can type in `a=Pow(b)` and the parser won't complain but it just won't be accepted because the correct solution is `Ax(x in a <-> x <( b)` or whatever.

Can we add the equivalents as follows?
- `sub` for ⊆
- `cup` for ∪
- `cap` for ∩
- `\` for setminus?
These will all be infix?

**Comment by gleachkr** [comment]
Sounds good. Parser additions will all be infix. I'll tweak that and add a mixed language with string predicates, and then see about translation exercises for these languages.

**Comment by rzach** [comment]
Wonderful thanks so much.

**Comment by gleachkr** [comment]
OK, we should now have translantion exercises with answers up to first-order equivalence for all the current arithmetic and set theory systems, including `openLogicExtendedArithNK`. Parser additions are done.

Down the road, we can add new translation types for coarser notions of equivalence that do algebra 101 rewrites or that rewrite inside of set abstracts, but that should probably be another issue.

So we still need:

1. A language for single-sorted higher-order arithmetic, extended with string predicates.
2. One or more set theory languages extended with string predicates, probably should just do extended variants of all three: strict, with operators, and with abstracts.
3. Translation exercises for these

Do we also want versions of OpenLogicNK that use these languages?

**Comment by rzach** [comment]
I lost track! What are the system strings for translation exercises/the `.` shortcuts? Or: where do I find them in the source?

**Comment by gleachkr** [comment]
Sorry, my bad, should have included those! You want `system="..."` where `...` is one of `elemenarySetTheory` (that's with operations like `cup`), `separativeSetTheory`(with separation, via set abstracts `{x<<y|φ(x)}`), `openLogicSTNK` (strict, ∈ only), `openLogicArithNK` and `openLogicExtendedArithNK`.

The listings of system names for a given language are usually in `src/Carnap/Languages/THELANGUAGEINQUESTION/Logic.hs`, in case that's helpful for future poking around.

**Comment by rzach** [comment]
Ah ok. But the superlanguage that has everything in it isn't available yet, right?  The proof checker works with these as `.openLogicArithNK` etc?  But we don't have *LK yet?

**Comment by gleachkr** [comment]
Yep, that's correct.

**Comment by rzach** [comment]
Things discovered so far: 

- [x] `.TreeDeduction .elementarySetTheory` etc works but  `.TreeDeduction system="elementarySetTheory"` doesn't.
- [x] `openLogicArithNK` etc. does not accept `!=`
- [x] NK playgrounds with `.openLogicArithNK` etc seems to only accept propositional formulas.
- [x] `.elementarySetTheory` doesn't seem to accept the symbols/keyboard equivalents above but not sure what breaks it.
- [x] Rendering formulas using `...`{system="openLogicExtendedArithNK"} etc. doesn't work yet.

- [x] `.TreeDeduction system="openLogicFOLNK"` works but `.TreeDeduction .openLogicFOLNK` doesn't.
- [x] `.Translate .FOL system="openLogicFOLNK"` doesn't seem to work.

My test document: https://carnap.io/shared/rzach@ucalgary.ca/olptest.md

**Comment by gleachkr** [comment]
`elementarySetTheory` is already a Montague ND system, so I think we need a separate name for a tree system (`openLogicESTNK`?)

Might also need to see about trying to render fewer parentheses in `openLogicArithNK`

**Comment by gleachkr** [comment]
OK, added `openLogicESTNK`. The tree deductions for elementary set theory in olptest.md now use system="openLogicESTNK" .

**Comment by rzach** [comment]
- [x] See https://carnap.io/shared/rzach@ucalgary.ca/systems.md#open-logic-project : Rendering formulas in the arithmetic systems cut off after a `<`
- [x] Should we shorten `openLogicExtendedArithNK` to `openLogicEArithNK` maybe?
- [x] Can the EST language display setminus as `\` instead of `/`?
- [x] The ST and EST languages don't allow s, t, u as variables

**Comment by gleachkr** [comment]
Maybe `openLogicExArithNK`, so that we can name uniformly and have `openLogicExSTNK`, without collision with `openLogicESTNK`?

**Comment by rzach** [comment]
Sounds good to me!

**Comment by rzach** [comment]
Another super minor thing: If you have infix predicates you can write things like `Exx<x`. It would be nice if there was a space after `Ex` whenever the next symbol is not a `(` (or, actually, always).

**Comment by gleachkr** [comment]
After shortening the name, I also made a few quick changes to documents on the server just to make sure nothing breaks.

**Comment by rzach** [comment]
Just realized: it would be nice to have ∅ (maybe as `0`) in `openLogicESTNK`. Is it ESTNK now or ExSTNK?

Should I make separate issues for a) making this also work in sequent calculus and b) model checker exercises?

**Comment by gleachkr** [comment]
> Just realized: it would be nice to have ∅ (maybe as 0) in openLogicESTNK.

Yes, definitely. Will do.

>  Is it ESTNK now or ExSTNK?

I was thinking that it'd be ESTNK, and that the system where you've got the set operations AND string predicates would be ExESTNK, "Extended Elementary Set Theory".

**Comment by rzach** [comment]
Ah I see. I couldn't think of a use case for ExEST but I suppose you need it if you want to introduce anything not already in EST.

**Comment by gleachkr** [comment]
I wonder what we should do about ∅ in the single-sorted higher-order arithmetic language, where using `0` as the notation will collide with the notation for zero?

**Comment by rzach** [comment]
Ok maybe just have `empty` then everywhere for consistency?

**Comment by gleachkr** [comment]
Or what about `{}`?

**Comment by rzach** [comment]
Yes let's display as ∅ and allow `empty` and `{}` as keyboard equivalents.

**Comment by gleachkr** [comment]
> Should I make separate issues for a) making this also work in sequent calculus and b) model checker exercises?

That'd be great.

**Comment by gleachkr** [comment]
Incidentally, would the openLogic*NK systems be an OK target for me to try to add runtime-specified axioms and inference rules (that you could include in the problem block options, separate from the premises, and maybe ultimately in the YAML header), or would it be preferable to have a separate system for that use? I'd try to do this in such a way that the current behavior would be the default, if no runtime axioms and rules are given.

**Comment by rzach** [comment]
You mean rather than ask for give a proof of A from B, C, D you can silently accept A, B, C as axioms and just say "Prove A from the theory of linear orders" or whatever?  And for the rules we'd be able to add an induction rule let's say? Or just logical rules? That would be amazing.

**Comment by gleachkr** [comment]
That's the idea! It'd be basically like derived rules in the Carnap book, but provided by the instructor. OK, so maybe we can call this set of NK systems a first pass (just for purposes of documentation and maybe mentioning it on the mailing list), and I'll then work on adding a runtime axiom mechanism that they can all use as another issue.

**Comment by rzach** [comment]
I added the new languages to the model checker for OLP issue #55 and made #239 for LK.

**Comment by gleachkr** [comment]
OK, empty set should now be implemented for `openLogicESTNK`.

**Comment by gleachkr** [comment]
First draft of the different extended systems is now live, so the mathematical openLogic systems are now:

- `openLogicSTNK`
- `openLogicExSTNK`
- `openLogicESTNK`
- `openLogicExESTNK`
- `openLogicSSTNK`
- `openLogicExSSTNK`
- `openLogicArithNK`
- `openLogicExArithNK`

The SST systems are the ones with separation abstracts in addition to the different elementary operations.

**Comment by gleachkr** [comment]
OK, the untyped higher order arithmetic system is ready for testing. The name is `openLogicExHOArithNK` - it's based on ExSST, so it ends up being something like the union of all the systems here.

**Comment by rzach** [comment]
On https://carnap.io/shared/rzach@ucalgary.ca/379%20Worksheet%20Derivations%20in%20NK.md problem 5 is:

    ```{.TreeDeduction .openLogicArithNK options="displayJSON prepopulate" init="now" submission="none"}
    W7.5 ∀x (x+0)=x, ∀x∀y(x+y')=(x+y)' :|-: (0'+0'')=0'''
    ```

but Carnap doesn't like it. It only complains if I have things to the left of the turnstyle.

**Comment by gleachkr** [comment]
Looks like a silly mistake on my part. Should now be fixed.

**Comment by rzach** [comment]
The openLogicSTNK and openLogicESTNK parsers don't like ⊥ (and its equivalents).

**Comment by gleachkr** [comment]
> The openLogicSTNK and openLogicESTNK parsers don't like ⊥ (and its equivalents).

Should be fixed!

**Comment by gleachkr** [comment]
Is this now pretty much done, modulo documentation?

**Comment by rzach** [comment]
While doing the documentation, ran into this: https://carnap.io/shared/rzach@ucalgary.ca/gentzen-ND.md
![Screenshot from 2021-03-20 14-40-15](https://user-images.githubusercontent.com/3122348/111884917-36a1d600-898a-11eb-8b8d-e9986869313f.png)
Not sure what's wrong.

**Comment by gleachkr** [comment]
Typo, I think - I fixed it on the server. But it looks like there's an 
issue with the formula rendering. I'll try to get to that too soon.

**Comment by gleachkr** [comment]
> Typo, I think - I fixed it on the server. But it looks like there's an issue with the formula rendering. I'll try to get to that too soon.

OK, the renderer is OK, actually, but the browser interprets `<x`, or anything with `<` followed by an alphabetical character as a malformed tag and drops it. Need to html escape the strings.

**Comment by gleachkr** [comment]
OK, the formula rendering issue should now be fixed.

**Comment by rzach** [comment]
Thanks! Closing this, the Documentation for the SST systems is https://github.com/Carnap/Carnap-Documentation/issues/11
