### ISSUE TITLE
Problem rendering truth tables

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#43]
In https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20III.md
the truth tables are all rendered incorrectly -- some the formulas at the top are off or missing. (It seems to do this only when system=thomasBolducAndZachTFL2019 not when system=thomasBolducAndZachTFL

**Comment by gleachkr** [comment]
Thanks! I should have some time to look at this one tomorrow afternoon.

**Comment by gleachkr** [comment]
OK. The trouble seems to be that the rendering for TFL2019 drops outermost parentheses. This turns  out to scramble the alignment between the symbols of the formula and the cells in the head row of the table. There are some other edge cases that might be similar, so I think I'm going to rewrite the TFL rendering function to take these into account. I should be able to get some time to do this tomorrow morning.

**Comment by gleachkr** [comment]
I just deployed something that should fix this. It has the side-effect of wrapping complex formulas in spaces, rather than parentheses, when rendering, but I think the visual effect is not too bad. If it looks good to you, I'll go ahead and mark this as closed.

**Comment by rzach** [comment]
Looks good!
