### ISSUE TITLE
Less permissive input options for syntax checking exercises?

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#45]
I finally made the plunge, and I'm happily using Carnap (and your book) instead of Logic 2010 this term for my classes! So far, I am really liking it! Thanks for making this.

One thing I have noticed: while it is nice to have lots of ways to enter in symbols, in addition to the official shortcuts recommended in the text, there are times when it confuses students. For example, several students didn't really understand what they were supposed to do for Chapter 1 parsing exercises, so they would enter 'and' instead of '/\', intending to describe the main connective rather than actually enter the symbol. Since that worked, they carried that confusion forward, and then got confused when similar answers didn't work on later problems.

So, at least in that context, it might make sense to be more restrictive about what shortcuts the parser allows?

**Comment by gleachkr** [comment]
That's great, thanks for using it!

About the symbols - yes, I see your point. The parsing examples there are supposed (partly) to help them learn the symbols, so using the more liberal parser there is potentially confusing. I'll tighten that up.
