### ISSUE TITLE
Parsing symbolic sentences in uploaded documents

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#48]
I notice that in the textbook, you use latex commands for all the symbolic sentences. Likewise, if I want to include a symbolic sentence in an uploaded document, I need to use the appropriate latex commands. As a convenience, it would be cool if instead I could leverage Carnap's parsing abilities for this. So, for example, I'd write

~~~
The following argument is not valid: `(P->Q)->(Q->R), Q->R :|-:  P->Q`{.Prop}
~~~

and Carnap would take care of parsing the sentences and displaying them appropriately. I have a pandoc lua-filter that handles this task for me (in a not very smart way) when writing handouts. It is really helpful to have a single canonical representation of a problem that I can cut and paste into all the different contexts where I might want it to appear.

**Comment by gleachkr** [comment]
This is a great idea. Also helps with typos :) I'll put it in the queue.

**Comment by gleachkr** [comment]
OK, this is now deployed. Rather than using class strings like ".Prop", I used attributes, so it's the slightly more verbose

    `(P->Q)`{system="prop"}

It'll work with both individual formulas and complete sequents.

**Comment by gleachkr** [comment]
Documentation has now been updated, so I think this one is done.
