### ISSUE TITLE
Incorrect Premise Stated in Example

### ISSUE THREAD

**Issue by JCDUFF** [Carnap/Carnap#5]
I believe there's a typo on Chapter 3 of the book. Please see the following:

"We begin with a show line, saying that we want to show R. We then write down the premises P, P → Q, Q → R on lines 2-4. Finally we use modus ponens (MP) to get Q on line 5 from the premises P and P → Q---so we write Q on line 5, and a justification (MP) to the right, with the line numbers of the premises P (line 2) and P → Q (line 3). We do the same thing, on the basis of premises Q and Q → R to assert R on line 6. _We then label that we have found **Q** on the basis of a direct derivation, by writing DD 6. The result looks like this:_

1. Show: R
2.     P    :PR
3.     P->Q :PR
4.     Q->R :PR
5.     Q    :MP 2,3
6.     **R**    :MP 4,5
7. :DD 6"

**Comment by gleachkr** [comment]
Absolutely correct. Thanks @JCDUFF, nice catch!

Fixed by ccf66dc.
