### ISSUE TITLE
Include function symbols in forallxYYC FOL systems

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#52]
Could you please make the 2019 Calgary forall x systems (`thomasBolducAndZachFOL2019`, `ZachFOL2019` and `ZachFOLPlus2019` for proofs) accept function symbols for parsing, symbolization, model checker, and derivation problems?  Function symbols are a-t possibly with subscripts, and must be followed by one or more terms (separated by commas, within parentheses).

**Comment by gleachkr** [comment]
No problem. I'll try to deploy the update tomorrow.

**Comment by rzach** [comment]
Doh I already asked for this in issue #25 ! Sorry.  But here's a question: 's' would be a good function symbol for successor, but s is also a variable.  Does it bother Carnap if a letter is both a function symbol and a variable?  If not, then let's also make s and t function symbols?

**Comment by gleachkr** [comment]
Sure thing. s and t have been added as function symbols. There's one part of the request that's still missing. At the moment subscripts are only allowed on the function symbol "f". I've got a fix, but it affects more than just forallxYCC, so I'll test a little more before I deploy that bit.

**Comment by gleachkr** [comment]
OK, all function symbols and constants now accept subscripts. (this involved a little reworking of how they're represented internally, but the new way makes more sense, I think. I'll be extending this to the other subscriptable pieces of syntax soon.)
