### ISSUE TITLE
Add OLP syntax as a system 

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#54]
Add a system for parsing formulas in FOL for use with OLP. That's just like forallx YYC 2019 (constants a-r, function symbols a-t, propositional and predicate symbols A-Z (ie arity >= 0), variables s-z, all possibly with subscripts). Variables are not required to occur free in the scope of a quantifier to be well formed (i.e., \forall x A is always well-formed, whether or not x occurs free in A).

The model checker should ideally allow formulas with free variables; however the proof systems operate only on sentences.

Syntax is defined here: http://builds.openlogicproject.org/content/first-order-logic/syntax-and-semantics/syntax-and-semantics.pdf but obvs we don't want to require every formula to be in "official" form. So for exercises we allow metavariables in the  #formulas.

**Comment by gleachkr** [comment]
Just finished adding subscripts to all variables. The OLP Gentzen ND checker uses the same parser as forallx YYC 2019, so I think this is now complete, modulo model-checker, which I think is being tracked elsewhere. Is there anything missing?

**Comment by gleachkr** [comment]
I think this can be closed. Feel free to reopen if not.
