### ISSUE TITLE
Typo in Chapter 6

### ISSUE THREAD

**Issue by JCDUFF** [Carnap/Carnap#6]
Please see the attached example. Should line 7 be ":ID 4 6"?
[Capture.pdf](https://github.com/gleachkr/Carnap/files/2982789/Capture.pdf)

**Comment by gleachkr** [comment]
Indeed it should, thank you! I'll push the change to the site this afternoon.

Fixed by 4541b0710a6c6c9d84665ec10cd09d88ecbe51b2.
