### ISSUE TITLE
saveRule option for proofs in assignments?

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#60]
Is it possible to include a "Rule Builder" playground directly in an assignment page? Or is the only page that can handle "Rule Builders" the special "rules index" page?

**Comment by gleachkr** [comment]
I think this ought to work with any assignment page. It's not documented, but at least for the carnap book systems (these are the only ones with custom derived rules at the moment), you should be able to do this by constructing an ordinary playground, and then using the option `submission="saveRule"`.
