### ISSUE TITLE
Outermost parens in forallx:YYC proofs

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#63]
In proofs using `.ZachFOL2019` and `.ZachTFL2019`, the rightmost formula among the premises in a proof gets its outermost parentheses displayed in the proof entry widget, others don't. See https://carnap.io/shared/rzach@ucalgary.ca/Practice%20Problems%20IV.md

**Comment by gleachkr** [comment]
Found the trouble. I should be able to fix it tomorrow.

**Comment by gleachkr** [comment]
Ok, should now be fixed.
