### ISSUE TITLE
Enrollment links not working?

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#68]
Maybe I'm doing the enrolment links wrong but I think they are not working. Here's what I've done:

-  Logged out of Carnap and all Google accounts
- Clicked on the enrolment link for a course https://carnap.io/enroll/Calgary%20Phil%20379%20L01%20Winter%202020
- That takes me to a Google login page, where I login with a dummy student gmail account
- Then I land at the carnap.io main page with a box that says "Now logged in"
- When I go to User Home it says "User is not enrolled"

Expected result: I should now be enrolled in the course and land on the student homepage rather than the front page.

**Comment by gleachkr** [comment]
Hm. What's the email associated with the dummy account? If you don't want to post it here, you can email it to me.

**Comment by gleachkr** [comment]
OK, seems like the issue is that the enrollment links don't update enrollment information on existing accounts - they only prefill part of the registration when doing account creation.  They should also update enrollment for existing accounts. I'll change that.

**Comment by rzach** [comment]
The most recent update does fix that, it seems. Just to be clear though about what it means if a student "changes" their enrolment: Are they then unenrolled in the other course? In other words, can a student only be enrolled in one active course at the same time? And if so, what happens to their submissions if they change the enrolment? 
I would say ideally it should be possible for a student to be in more than one course, and that submission records should be kept until **the instructor** explicitly drops the student. (Otherwise we'll get cases where students inadvertently change their registration or drop a course but then change their minds, and all their submissions are gone.)

**Comment by gleachkr** [comment]
They are then unenrolled from the other course. But this doesn't cause any work to be lost, all their submissions are preserved. They can switch back to the original course by updating their user information on their user page. This information should probably be included on the "change enrollment" page. I'll add a bit of a disclaimer there.

Multiple enrollments would be ideal, I agree, but it would be a pretty big change, I think - maybe a separate issue for that?

**Comment by rzach** [comment]
Done, issue #75

**Comment by rzach** [comment]
BTW there is a hovering text box in the top left corner that says "Enrolment changed" and sometimes "Now logged in". It obscures the text underneath. Maybe it can disappear automatically after a few seconds or get a "close" button?
