### ISSUE TITLE
Student ID field when registering?

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#70]
For registered students, Carnap gives me three data points: google account email address, last name, and first name. My University roster gives me three data points: a university ID that is identical to the slug of their university email address (e.g., mine is `desanso` and my email address is `desanso@ilstu.edu`), university ID number, and name (first name, last name, and sometimes middle initials, all as a single string). This makes it a bit of a juggling act getting their homework scores into my gradebook.

So, I'd suggest asking the students for an ID when they register, perhaps with a note asking them to first check with their instructor about what ID they should use, and perhaps with the option to later edit that ID after they have registered. (Logic 2010 asks them for their ID number, but Carnap shouldn't assume that the appropriate ID is a number.)

**Comment by loighic** [comment]
Ah, I knew that I'd seen this somewhere. I just suggested it in the google group.

**Comment by gleachkr** [comment]
OK, done! Registration now allows students to enter an ID, this ID is visible in grade export, and it can be edited on the user page.
