### ISSUE TITLE
ZachFOL2019 proof checker does not accept correct proof

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#71]
In 
https://carnap.io/shared/rzach@ucalgary.ca/issue71.md
all the lines have + and the sequent for the last line corresponds to the problem but there's a warning triangle that says
"This proof does not establish that the conclusion follows from the premises"

**Comment by gleachkr** [comment]
Thanks! This has to do with the nested quantifiers. It looks like there's variable-binding-cleanup step I missed before comparing the sequent established at the end of the proof and the sequent to be proved. Adding the cleanup makes both proofs check. I'll deploy the fix with the rest of the changes tomorrow.

**Comment by rzach** [comment]
Works! Thanks for the quick turnaround!
