### ISSUE TITLE
Grade export missing email field

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#74]
I just exported grades, and the CSV is missing the student email field, which breaks my spreadsheet import!

**Comment by gleachkr** [comment]
Thanks, will fix tomorrow!

**Comment by gleachkr** [comment]
Just deployed the update. Does this help with the spreadsheet import?

**Comment by dsanson** [comment]
Much better. The email addresses are back!

It still breaks my spreadsheet. The culprit is the extra spaces that have been added after each comma:

    student@example.com, Smith, John, 50, 0, 45, 10, 6, 0...

Even though CSV isn't all that standardized, here is what the wikipedia article says:

> In some CSV implementations[which?], leading and trailing spaces and tabs are trimmed (ignored). Such trimming is forbidden by RFC 4180, which states "Spaces are considered part of a field and should not be ignored."
>
> ~~~
> 1997, Ford, E350
> not same as
> 1997,Ford,E350
> ~~~

MS Excel honors those extra spaces. So the last name in my example is " Smith" instead of "Smith". So the output should be:

    student@example.com,Smith,John,50,0,45,10,6,0...

Also, I don't know what kind of characters you allow in student names, but probably the names should be in double quotes:

    student@example.com,"Smith","John",50,0,45,10,6,0...

**Comment by gleachkr** [comment]
OK, this should be fixed once the latest deploy finishes. All the text fields are now quote-enclosed, and any internal quotes will be properly escaped, just in case some student decides to name themselves something like `","1000000`
