### ISSUE TITLE
Shortcut reference links

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#77]
I've noticed that Carnap doesn't support shortcut reference links:

    A link like [this] won't work. But a link like [this][] works fine.

    [this]: example.com

Is that intentional? If so, it would be nice (eventually) to have documentation of which pandoc markdown features are supported and which not.

**Comment by gleachkr** [comment]
No specific reason. So, I went ahead and added this to the list of extensions. I also documented the available extensions in the main document on pandoc's markdown.
