### ISSUE TITLE
Links to assignments, redirects, and logging in.

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#79]
Current behavior: If I follow a link to an assignment, and I am not already logged in to Carnap, I get redirected to the main page, with an overlay message saying "you to need to be logged in to access assignments." I can then log in, at which point I am taken to my User (or Instructor) page. 

Ideal behavior: If I follow a link to an assignment and I am not logged in, I get redirected to the login page, and after logging in, I get redirected to the original link.

**Comment by rzach** [comment]
This is also the last point in issue #14

**Comment by dsanson** [comment]
Closing as redundant!
