### ISSUE TITLE
Allow direct links to exercises

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#83]
Low priority!

I was just helping a student with a problem on a discussion forum, and realized that it would be nice to be able to link directly to the exercise. In this case, it was exercise 10.8 from Chapter 9 of the Carnap book. Something like:

    https://carnap.io/book/9#exercise-10.8

would be brilliant, both for exercises in the book, and for exercises in uploaded documents. Just a matter, I think, of adding an id to the relevant div:

   <div class="exercise" id="exercise-10.8">

I guess that won't quite work for shared versions of documents that contain more than one version of the same numbered exercise.

**Comment by gleachkr** [comment]
Turned out to be a very easy tweak, so I just went ahead and did that. The format for the tags is just the one you're describing, "exercise-" followed by the problem lable.
