### ISSUE TITLE
URGENT! Assignments displaying all alternate problems to students

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#86]
Suddenly, my "quizzes" seem to be displaying all of the problems to the students. See the screenshot, where the URL is an assignments URL, not a shared URL, and it is showing all the versions of problem TTTQ1.1:

![1585851126](https://user-images.githubusercontent.com/14331/78283562-91c18b00-74e3-11ea-9285-2f0c44f15994.png)

This is a bit problematic!

**Comment by gleachkr** [comment]
Sorry, it must be the last update. I'll roll it back.

**Comment by dsanson** [comment]
Thanks!

**Comment by gleachkr** [comment]
OK, build and deployed. Could you check to see if this corrects the behavior?

**Comment by dsanson** [comment]
Yes, that fixed the problem. It must have been something about the changes made to add id tags to the exercises?

**Comment by gleachkr** [comment]
Great! Yes, that's probably it. Two possibilities - I did something very dumb and overwrote the "randomizing" pandoc filter, or I did something regular-dumb and changed the exercise format in a way that the randomizer filter misses. Let me take a look.

**Comment by gleachkr** [comment]
Looks like just regular dumb. (a little harder to diagnose unfortunately). I'll figure it out make sure to test randomization before trying to deploy again.

**Comment by gleachkr** [comment]
Looks like the pattern match for the randomizer asssumed that the exercises had no id tag. So should actually be an easy fix. Thanks for the alert!

**Comment by gleachkr** [comment]
Ok, now exercises should have tags and should also randomize properly. I've tested this on the server and it's working for me. I think this can be closed if it's working for you.

**Comment by dsanson** [comment]
Yes! Thanks for handling this so promptly. I only got one very confused email from a student!
