### ISSUE TITLE
Correct proof not accepted by Carnap

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#87]
The proof at https://carnap.io/shared/rzach@ucalgary.ca/issue87.md seems to me to be correct, all lines check out, but Carnap doesn't like it.

**Comment by rzach** [comment]
Looks like a similar problem to issue #71

**Comment by gleachkr** [comment]
It does. Hopefully a similar fix.

**Comment by gleachkr** [comment]
I think it's likely the same type of thing - variable bindings need to be sanitized somewhere - but I haven't pinned it down yet. I'll give it another try tomorrow.

**Comment by gleachkr** [comment]
OK, a fix is currently being deployed. It looks like this was actually a version of #36. In a moment of weakness a little while back, I apparently relaxed the original solution there slightly, thinking that we could skip a certain round of sanitization. That's evidently not the case. Going back to the original full scrub fixes this one.
