### ISSUE TITLE
Example lists not properly numbered

### ISSUE THREAD

**Issue by dsanson** [Carnap/Carnap#88]
I've noticed that example lists are not properly numbered. That is,

```
Blah blah.

@.   Example

Blah blah.

@.   Example
```

will render with both items numbered as "1." This isn't new---I noticed it awhile back but hadn't gotten around to mentioning it. Here is an example of a real document in which this happens:

https://carnap.io/shared/dsanson@gmail.com/Monadic%20PL%20Symbols%20to%20English

**Comment by gleachkr** [comment]
~Hm - Example lists are working in the textbook at least. Do you still have the problem when you use the syntax `(@)` rather than `@.`?~

Nope, that's not it.

**Comment by rzach** [comment]
Markdown documentation: "List items may consist of multiple paragraphs. Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab." Did you indent the second "Blah blah"?

**Comment by gleachkr** [comment]
OK. Looks like a css problem. Will fix.

**Comment by gleachkr** [comment]
Minor preference question before deploying. Do you prefer example lists with the list counter in the usual place, like

```
1. Example

blah

2. Example
```

Or in the numbered equation style, like

```
Example                                        (1)

blah

Example                                        (2)
```

?

**Comment by gleachkr** [comment]
I'll put in a vote for the equation style. If that's ok, then I'll deploy the fix this afternoon.

**Comment by rzach** [comment]
Does that change all numbered lists to equations? If so, I'd vote against it.

**Comment by gleachkr** [comment]
No, just numbered example lists, created with the `@` syntax here: 

https://pandoc.org/MANUAL.html#numbered-example-lists

Agreed, would be a bad idea for lists in general.

**Comment by dsanson** [comment]
I’d put in a vote for the usual place. But I can see the reasons for either.

**Comment by gleachkr** [comment]
Ok. I'll go with the usual place.

**Comment by gleachkr** [comment]
Currently deploying. Sorry for the delay, spent most of the day dealing with a catastrophic laptop failure.
