### ISSUE TITLE
Can't view problem set linked from student page

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#95]
Links to problem sets from student pages are 
```
carnap.io/assignments/Problem Set Name.md
```
and you get a "you need to be enrolled in a course to access assignments" error when you click on it as instructor.  This shouldnt happen anymore and wouldn't if the links were 
```
carnap.io/assignments/Course Name/Problem Set Name.md
```

**Comment by gleachkr** [comment]
Right, sorry about that. Should be able to fix tomorrow morning.

**Comment by gleachkr** [comment]
OK, I've set this up. It requires some rejiggering of authentication for assignments, so I'm going to do a little more testing before deploying.

**Comment by gleachkr** [comment]
Deploying. This pretty much depreciates the shorter assignment links, but I'll leave them functional for now in case anyone has bookmarked anything.
