### ISSUE TITLE
Save submissions other than proofs

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#98]
Proofs are saved and shown on the exam grading page, but answers to other kinds of exercises only if they are incorrect.  Should save and show all exercise types even when autograded.

**Comment by gleachkr** [comment]
I think everything where there's meaningful data to display is now covered, except for truth tables.

**Comment by rzach** [comment]
Cool!  I looked at a problem set with symbolizations on it:  https://carnap.io/shared/rzach@ucalgary.ca/279%20Problem%20Set%205%20F20.md problems 5.4/5/6 & 18 display fine in the PS and accept submissions, but in the review they don't show:
![Screenshot from 2020-10-08 11-53-23](https://user-images.githubusercontent.com/3122348/95495615-e6473680-095c-11eb-9638-e6bb559f4b9e.png)
New issue?

**Comment by gleachkr** [comment]
OK, that issue should now be fixed.

**Comment by rzach** [comment]
Thanks!
