### ISSUE TITLE
Exam proof grading: proof may obscure extra credit box

### ISSUE THREAD

**Issue by rzach** [Carnap/Carnap#99]
If the proof is too wide, it will overlay the extra credit box rather than push that box down or something.
![Screenshot_2020-04-18 https carnap io](https://user-images.githubusercontent.com/3122348/79645378-31ca1600-816c-11ea-9bf3-6e92314dc2c4.png)

**Comment by gleachkr** [comment]
The easiest thing here is to make the proof scrollable in the x-axis, and allow the user to scroll the extra content into view. Does that sound OK?

**Comment by rzach** [comment]
I think that would be great, yes.

**Comment by gleachkr** [comment]
Ok, should be done!
